force-app/main/default/objects/QB_Company__c/QB_Company__c.object-meta.xml
<CustomObject>
    <description>The QuickBooks Company (aka BAC) is a perfect copy of your QuickBooks Customer</description>
    <label>QB Company</label>
    <nameField>
        <displayFormat>BW - {0000}</displayFormat>
        <label>QuickBooks Company #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QB Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Company__c/fields/QB_City__c.field-meta.xml
<CustomField>
    <fullName>QB_City__c</fullName>
    <label>Town / City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>QB_Company_Name__c</fullName>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Country__c.field-meta.xml
<CustomField>
    <fullName>QB_Country__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Default_Terms_Ref__c.field-meta.xml
<CustomField>
    <fullName>QB_Default_Terms_Ref__c</fullName>
    <label>Default Terms Ref</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Email__c.field-meta.xml
<CustomField>
    <fullName>QB_Email__c</fullName>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_External_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_External_Id__c</fullName>
    <label>QB External Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Family_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>QB_Family_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Given_First_Name__c.field-meta.xml
<CustomField>
    <fullName>QB_Given_First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Other_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>QB_Other_Phone_Number__c</fullName>
    <label>Other Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>QB_Phone_Number__c</fullName>
    <label>Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>QB_Postal_Code__c</fullName>
    <label>Postal / Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Preferred_Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>QB_Preferred_Delivery_Method__c</fullName>
    <label>Preferred Delivery Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Region__c.field-meta.xml
<CustomField>
    <fullName>QB_Region__c</fullName>
    <label>State / Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>QB_Street_Address__c</fullName>
    <label>Street Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Sync_Token__c.field-meta.xml
<CustomField>
    <fullName>QB_Sync_Token__c</fullName>
    <label>Sync Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CompanyTriggerHandler.cls
public without sharing class CompanyTriggerHandler {
    public CompanyTriggerHandler() {

    }


    public static void handleCompanyData(List<QB_Company__c> companyOldData,List<QB_Company__c> companyNewData){
            
        // get main values for callout
        String comId         =  companyNewData[0].Id;
        String qbExternalId  =  companyNewData[0].QB_External_Id__c;
        String curSyncToken  =  companyNewData[0].QB_Sync_Token__c;

        String fName         = '';
        String lName         = '';
        String email         = '';
        String comName       = '';
        String displayName   = '';
        String phone         = '';
        String mobile        = '';
        String state         = '';
        String postcode      = '';
        String city          = '';
        String country       = '';
        String street        = '';
        String paymentRef    = '';
        String termRef       = '';


        // check values
        if(companyNewData[0].QB_Given_First_Name__c != companyOldData[0].QB_Given_First_Name__c){
            //System.debug('Not Changed '+companyNewData[0].QB_Phone_Number__c+' & '+companyOldData[0].QB_Phone_Number__c);
            fName = companyNewData[0].QB_Given_First_Name__c;
        }

        // check values
        if(companyNewData[0].QB_Family_Last_Name__c != companyOldData[0].QB_Family_Last_Name__c){            
            lName = companyNewData[0].QB_Family_Last_Name__c;
        }


         // check values
         if(companyNewData[0].QB_Company_Name__c != companyOldData[0].QB_Company_Name__c){            
            comName = companyNewData[0].QB_Company_Name__c;
        }

         // check values
         if(companyNewData[0].QB_Email__c != companyOldData[0].QB_Email__c){            
            email  = companyNewData[0].QB_Email__c;
        }

         // check values for phone
         if(companyNewData[0].QB_Phone_Number__c != companyOldData[0].QB_Phone_Number__c){            
            phone  = companyNewData[0].QB_Phone_Number__c;
        }

         // check values for phone
         if(companyNewData[0].QB_Other_Phone_Number__c != companyOldData[0].QB_Other_Phone_Number__c){            
            mobile  = companyNewData[0].QB_Other_Phone_Number__c;
        }

        if(companyNewData[0].QB_Region__c != companyOldData[0].QB_Region__c){            
            state  = companyNewData[0].QB_Region__c;
        }
        if(companyNewData[0].QB_City__c != companyOldData[0].QB_City__c){            
            city  = companyNewData[0].QB_City__c;
        }
        if(companyNewData[0].QB_Street_Address__c != companyOldData[0].QB_Street_Address__c){            
            street  = companyNewData[0].QB_Street_Address__c;
        }
        if(companyNewData[0].QB_Country__c != companyOldData[0].QB_Country__c){            
            country  = companyNewData[0].QB_Country__c;
        }
        if(companyNewData[0].QB_Postal_Code__c != companyOldData[0].QB_Postal_Code__c){            
            postcode  = companyNewData[0].QB_Postal_Code__c;
        }
        if(companyNewData[0].QB_Default_Terms_Ref__c != companyOldData[0].QB_Default_Terms_Ref__c){            
            termRef  = companyNewData[0].QB_Default_Terms_Ref__c;
        }
        if(companyNewData[0].QB_Preferred_Delivery_Method__c != companyOldData[0].QB_Preferred_Delivery_Method__c){            
            paymentRef  = companyNewData[0].QB_Preferred_Delivery_Method__c;
        }

        
        System.debug('Email '+email);
        System.debug('curSyncToken '+curSyncToken);
        //curSyncToken = '9';

        displayName = fName+lName;
        system.debug('Display Name :: '+displayName);

        String fullyQuaName  =  'Jack Knight : '+displayName;
        
        //String json   = '      "Id": "95", ';

        String json = '{'+
        '      "Id": '+'"'+qbExternalId+'", ';
        
        
        if(fullyQuaName!=''){
            json+='   "FullyQualifiedName": '+'"'+fullyQuaName+'", ';
        } 

        if(displayName!=''){
            json+='      "DisplayName": '+'"'+displayName+'", ';
        }

        if(displayName!=''){
            json+='      "CompanyName": '+'"'+comName+'", ';
        }

        if(email!=''){ 
            json+='   "PrimaryEmailAddr": {'+
            '          "Address": '+'"'+email+'"'+ 
            '      }, ';
        }
        
        if(phone!=''){
            json+='  "PrimaryPhone": {'+
                '    "FreeFormNumber": '+'"'+phone+'"'+ 
                '  }, ';
        }

        if(mobile!=''){
            json+='  "Mobile": { '+
                '  "FreeFormNumber": '+'"'+mobile+'"'+ 
            '  }, ';
        }
        if(state!=''){
        json+='  "BillAddr": {'+
        '    "CountrySubDivisionCode": '+'"'+state+'",';
        }
        if(city!=''){
        json+='    "City": '+'"'+city+'", ';
        }
        if(postcode!=''){
        json+='    "PostalCode":'+'"'+postcode+'", ';
        }
        if(street!=''){
        json+= '    "Line1": '+'"'+street+'", ';
        }
        if(country!=''){
        json+= '    "Country": '+'"'+country+'" '+
        '  }, ';
        }
        if(termRef!=''){
            json+='  "SalesTermRef": { '+
                '  "value": '+'"'+termRef+'"'+ 
                '  }, ';
        }
        if(paymentRef!=''){
            json+=        ' "PaymentMethodRef": { '+
                '  "value": '+'"'+paymentRef+'"'+ 
                ' },' ;
        }       
		
		json+='      "MiddleName": "B", '+
		'      "FamilyName": '+'"'+fName+'", '+
		'      "GivenName": '+'"'+lName+'", '+
		/*'      "SyncToken": '+'"'+curSyncToken+'", '+*/
        '      "SyncToken": '+'"'+curSyncToken+'", '+  
		'      "sparse": true'+
		'    } ';

        System.debug('JSON '+json);

        //QB_External_API.updateCustomerAndSync(json,comId,curSyncToken);
        //companyNewData[0].QB_Sync_Token__c+1;
    }
}