force-app/main/default/objects/QB_Integration_Log__c/QB_Integration_Log__c.object-meta.xml
<CustomObject>
    <label>QB Integration Log</label>
    <nameField>
        <displayFormat>QB_Log_{000000}</displayFormat>
        <label>QB Integration Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QB Integration Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Integration_Log__c/fields/QB_Consumed_Api__c.field-meta.xml
<CustomField>
    <fullName>QB_Consumed_Api__c</fullName>
    <label>Consumed API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Integration_Log__c/fields/QB_Request_Body__c.field-meta.xml
<CustomField>
    <fullName>QB_Request_Body__c</fullName>
    <label>Request Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QB_Integration_Log__c/fields/QB_Request_URL__c.field-meta.xml
<CustomField>
    <fullName>QB_Request_URL__c</fullName>
    <label>Request URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/QB_Integration_Log__c/fields/QB_Response_Body__c.field-meta.xml
<CustomField>
    <fullName>QB_Response_Body__c</fullName>
    <label>Response Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QB_Integration_Log__c/fields/QB_Result__c.field-meta.xml
<CustomField>
    <fullName>QB_Result__c</fullName>
    <label>Result</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Integration_Log__c/fields/QB_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>QB_Status_Code__c</fullName>
    <label>Status Code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/QB_Integration_Log_Utils.cls
public class QB_Integration_Log_Utils {
    private static List<QB_Integration_Log__c> qbLogsToInsert = new List<QB_Integration_Log__c>();
    public static void insertIntegrationLog(HttpRequest req, HttpResponse res, String apiFriendlyName, String result){
        System.debug('Entered Integration log Utils');
        QB_Integration_Log__c log = new QB_Integration_Log__c();
        log.QB_Consumed_API__c = apiFriendlyName;
        log.QB_Request_URL__c = req.getEndpoint();
        log.QB_Request_Body__c = req.getBody();
        log.QB_Status_Code__c = res.getStatusCode();
        log.QB_Response_Body__c = res.getBody();
        log.QB_Result__c = result;
        insert log;
        qbLogsToInsert.add(log);
    }
    
    public static void insertWebhookIntegrationLog(RestRequest req,String apiFriendlyName, String result){
        System.debug('Entered Integration log Utils');
        QB_Integration_Log__c log = new QB_Integration_Log__c();
        log.QB_Consumed_API__c = apiFriendlyName;
        //log.QB_Request_Body__c = req;
        //log.QB_Response_Body__c = res;
        log.QB_Result__c = result;
        insert log;
        qbLogsToInsert.add(log);
    }
    public static void insertNewLogs(){
        insert qbLogsToInsert;
        qbLogsToInsert.clear();
    }
}