force-app/main/default/objects/Account/fields/Agent_to_Bill__c.field-meta.xml
<CustomField>
    <fullName>Agent_to_Bill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <formula>breadwinner_qbo__Total_Amount_Due__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <formula>Indicated_Premium__c - (Indicated_Premium__c * VALUE(TEXT( Commission__c )))/100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Applicants/Insureds</relationshipLabel>
    <relationshipName>Applicants_Insureds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/QB_External_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>QB External Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Amount_Received__c</fullName>
    <formula>Invoice__r.breadwinner_qbo__Amount_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Insured__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/QB_Invoice__c.field-meta.xml
<CustomField>
    <fullName>QB_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QB Invoice</label>
    <referenceTo>QB_Invoice__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/QB_Company__c.object-meta.xml
<CustomObject>
    <description>The QuickBooks Company (aka BAC) is a perfect copy of your QuickBooks Customer</description>
    <label>QB Company</label>
    <nameField>
        <displayFormat>BW - {0000}</displayFormat>
        <label>QuickBooks Company #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QB Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Company__c/fields/QB_External_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_External_Id__c</fullName>
    <label>QB External Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/QB_Invoice__c.object-meta.xml
<CustomObject>
    <label>QB Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QB Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QB Invoices</relationshipLabel>
    <relationshipName>QB_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Credited__c.field-meta.xml
<CustomField>
    <fullName>Amount_Credited__c</fullName>
    <description>Amount Credited will be calculated only if any Credit Memo applied to Invoice</description>
    <label>Amount Credited</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Overdue__c.field-meta.xml
<CustomField>
    <fullName>Amount_Overdue__c</fullName>
    <formula>IF( Due_Date__c &lt; TODAY(), Amount_Due__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Overdue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Amount_Received__c</fullName>
    <label>Amount Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <description>City of the Billing Address</description>
    <label>Billing City/Town</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <description>Country of Billing Address</description>
    <label>Billing Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Postal_Code__c</fullName>
    <label>Billing Postal / Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_State__c</fullName>
    <description>State of the Billing Address</description>
    <label>Billing State/Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street_Address__c</fullName>
    <label>Billing Street Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Credit_Memo_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo_Total_Amount__c</fullName>
    <label>Total Credit / Refund Amoun</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Days_Overdue__c.field-meta.xml
<CustomField>
    <fullName>Days_Overdue__c</fullName>
    <formula>IF(OR(Amount_Overdue__c == 0.00,ISBLANK(Amount_Overdue__c)) , null, TODAY() - Due_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Overdue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>The e-mail address where the invoice is sent</description>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Email_Status__c.field-meta.xml
<CustomField>
    <fullName>Email_Status__c</fullName>
    <description>Email status of the invoice.
Values: NotSet, NeedToSend, EmailSent</description>
    <label>Email Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Inception_Date__c.field-meta.xml
<CustomField>
    <fullName>Inception_Date__c</fullName>
    <formula>Invoice_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inception Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Message_Displayed__c.field-meta.xml
<CustomField>
    <fullName>Message_Displayed__c</fullName>
    <label>Message Displayed on Invoice</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/QB_Company__c.field-meta.xml
<CustomField>
    <fullName>QB_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QB Company</label>
    <referenceTo>QB_Company__c</referenceTo>
    <relationshipLabel>QB Invoices</relationshipLabel>
    <relationshipName>QB_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/QB_External_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_External_Id__c</fullName>
    <label>QB External Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Statement_Memo__c.field-meta.xml
<CustomField>
    <fullName>Statement_Memo__c</fullName>
    <label>Statement Memo</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Sync_Token__c.field-meta.xml
<CustomField>
    <fullName>Sync_Token__c</fullName>
    <label>Sync Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Line_Item__c/QB_Line_Item__c.object-meta.xml
<CustomObject>
    <label>QB Line Item</label>
    <nameField>
        <label>QB Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QB Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <description>Master of the line item</description>
    <label>Invoice</label>
    <referenceTo>QB_Invoice__c</referenceTo>
    <relationshipLabel>QB Line Items</relationshipLabel>
    <relationshipName>QB_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QB_Line_Item__c/fields/Product_Service__c.field-meta.xml
<CustomField>
    <fullName>Product_Service__c</fullName>
    <description>Name of Product/Service</description>
    <label>Product/Service</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateInvoiceBatch.cls
global class CreateInvoiceBatch implements Database.Batchable<sObject>,  Database.AllowsCallouts , Database.Stateful {
    
    public  Database.QueryLocator  start(Database.BatchableContext BC) {
        
        //System.debug('QueryLocator');
        String Query = 'SELECT Id,QB_Company__c,Billing_Street_Address__c,Billing_City__c,Billing_State__c,Billing_Postal_Code__c,Billing_Country__c,Email_Status__c,Email__c,Policy__c,Name,Terms__c,Account__c,Account__r.QB_External_Id__c,Account__r.Name,Account__r.Agent_to_Bill__r.Name,Due_Date__c,Invoice_Date__c,Inception_Date__c,Amount_Received__c,Amount_Credited__c,Amount_Due__c,Amount_Overdue__c,Discount_Amount__c,Credit_Memo_Total_Amount__c,Statement_Memo__c,Days_Overdue__c,Total__c,Message_Displayed__c,(SELECT Id,Name,Rate__c,Quantity__c,Amount__c,Product_Service__c,Description__c FROM QB_Line_Items__r) FROM QB_Invoice__c Where Account__r.QB_External_Id__c!= NULL  Limit 1 ';
        //if(System.Test.isRunningTest()) Query ='SELECT Account.Name,Sync_Token__c,Account.QBO_External_UID__c,Description,Name,ItemRef_Value__c,ItemtRef_Name__c, Balance_Due__c, OwnerId, TotalAmount, Deposit__c, OrderNumber,(SELECT Product2Id,Product2.Name,Product2.QB_External_Id__c,UnitPrice,Quantity FROM OrderItems ) FROM Order LIMIT 1'; 
        
        return Database.getQueryLocator(Query);
        
    }    
    
    public void execute(Database.BatchableContext BC, List<QB_Invoice__c> scope) { 
        Integer count;
        Integer iteration;
        String JsonBody='';
        string Temp1='';
        string Temp2='';
        string Temp3='';
        String endpoint;
        List<QB_Invoice__c> OrderToUpdate = new List<QB_Invoice__c>();
        for(QB_Invoice__c orderObj1 : scope)
        {        
            Temp1 = '{\n'+         
                '  "Line": '+'[\n';
        }
        for(QB_Invoice__c orderObj : scope)
        {
            Temp2='';
            count = orderObj.QB_Line_Items__r.size();
            iteration = 0;
            if(!orderObj.QB_Line_Items__r.isEmpty()){
                for(QB_Line_Item__c orderItemIterate : orderObj.QB_Line_Items__r ){
                    iteration++;
                    decimal tempDecimal;
                    String serviceName = null;
                    String serviceId   = null;
                    if(orderItemIterate.Product_Service__c=='Commissions'){
                        orderItemIterate.Amount__c = -orderItemIterate.Amount__c;
                        tempDecimal = orderItemIterate.Quantity__c * orderItemIterate.Amount__c;
                        serviceName = 'Comission';
                        serviceId   = '20';
                    }else{
                        tempDecimal = orderItemIterate.Quantity__c * orderItemIterate.Amount__c;
                        serviceName = 'Gross Premium';
                        serviceId   = '23';
                    }
                    Temp2 =  '    {\n'+
                        '      "DetailType": ' + '"'+'SalesItemLineDetail'+'", \n'+
                        '      "Amount": '+'"'+tempDecimal+'", \n';
                        if(orderItemIterate.Description__c != null){
                            Temp2+='      "Description" :'+'"'+orderItemIterate.Description__c+'", \n';
                        }  
                 Temp2+='      "SalesItemLineDetail": {\n'+
                        '        "ItemRef": {\n'+
                        //'          "name": '+'"'+serviceName+'", \n'+
                        '          "value": '+'"'+serviceId+'"\n'+
                        '        },\n'+
                        '        "Qty": '+'"'+orderItemIterate.Quantity__c+'",\n'+
                        '        "UnitPrice": '+'"'+orderItemIterate.Amount__c+'"\n'+
                        '      }\n'+
                        '    }\n';
                    //System.debug('Temp2##################'+Temp2);
                    if(count == 1){   Temp2=Temp2;   }else{ if(count == iteration){  Temp2=Temp2;  }else{  Temp2=Temp2+',';  }  }
                    //System.debug('Temp2##################'+Temp2);
                    Temp1+=Temp2 ;  
                }
                
                Temp3 = '  ], \n'+
                    '  "Deposit": '+'"'+orderObj.Amount_Credited__c+'", \n'+   
                    '  "Balance": '+'"'+orderObj.Total__c+'", \n'+ 
                    '  "SalesTermRef": { '+
                    '    "value": "1" '+
                    '        },\n';        
                if(orderObj.Statement_Memo__c!=null){
                            Temp3+='  "PrivateNote": '+'"'+orderObj.Statement_Memo__c+'", \n';
                        }
                //crInvoiceData.Message_Displayed__c!='' || crInvoiceData.Message_Displayed__c!=null
                        if(true){
                            orderObj.Message_Displayed__c = 'Customer Message Here';
                            Temp3+='  "CustomerMemo": { '+
                                   '    "value": '+'"'+orderObj.Message_Displayed__c+'"\n'+
                                   '        },\n';
                        }

                        if(orderObj.Email__c!=null){
                            Temp3+='  "BillEmail": { '+
                                   '    "Address": '+'"'+orderObj.Email__c+'"\n'+
                                   '        },\n';
                        }

                        Temp3+='  "TxnDate" : '+'"'+orderObj.Invoice_Date__c+'", \n'+ 
                        '  "DueDate" : '+'"'+orderObj.Due_Date__c+'", \n'+ 
                        '  "CustomerRef": {\n'+
                        '    "name": '+'"'+orderObj.Account__r.Name+'", \n'+      
                        '    "value": '+'"'+orderObj.Account__r.QB_External_Id__c+'"\n'+
                        '  }\n'+
                        '}' ;
                 JsonBody +=Temp1+Temp3;
              //System.debug('JsonBody'+JsonBody);
                
                HttpRequest req = new HttpRequest();
                HttpResponse res = new HttpResponse();
                Http http = new Http();
           		endpoint = 'callout:QuickbooksCredentialsSandbox'+'/v3/company/4620816365236175040/invoice?minorversion=65';
                // endpoint = 'callout:QuickBookCredendial'+'/company/4620816365230257050/invoice?minorversion=65';   
                //req.setHeader('Authorization', header);
                req.setEndpoint(endpoint);
                req.setMethod('POST');
                req.setHeader('Content-Type', 'application/json');
                req.setHeader('accept', 'application/json');
                req.setBody(JsonBody);
                res = http.send(req); 
              //System.debug('Status Code @@ '+res.getStatusCode());
                
                if(res.getStatusCode() == 200)
            {
                
                Map<String,Object> QueryResponseMap =(Map<String,Object>) JSON.deserializeUntyped(res.getBody());   
                Map<String,Object> Invoice =(Map<String,Object>) QueryResponseMap.get('Invoice');  
              //System.debug('Invoice Data @@ '+Invoice); 
              //System.debug('Inv Id Ret '+(String)Invoice.get('Id'));
                orderObj.QB_External_Id__c = (String)Invoice.get('Id');
                orderObj.Sync_Token__c  = '0';
                if(orderObj.QB_External_ID__c!=''){
                    update orderObj; 
                }
                
                QB_Integration_Log_Utils.insertIntegrationLog(req, res, 'customerReadAll', 'Invoice created Successfully');
            }
            else{ 
                QB_Integration_Log_Utils.insertIntegrationLog(req, res, 'customerReadAll', 'Error in Customer creation');
            }  
                
            }
            
        }
        //if(!System.Test.isRunningTest()) update OrderToUpdate;
        
    }
    
    
    
    public void finish(Database.BatchableContext BC){
        
      //System.debug('Finish called');
    }
}