force-app/main/default/objects/Account/fields/Agent_to_Bill__c.field-meta.xml
<CustomField>
    <fullName>Agent_to_Bill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <formula>breadwinner_qbo__Total_Amount_Due__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <label>Commission</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Contact_Person_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_First_Name__c</fullName>
    <label>Contact Person First Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contact_Person_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Last_Name__c</fullName>
    <label>Contact Person Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <formula>Indicated_Premium__c - (Indicated_Premium__c * VALUE(TEXT( Commission__c )))/100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Indicated_Premium__c.field-meta.xml
<CustomField>
    <fullName>Indicated_Premium__c</fullName>
    <formula>199 + ( Number_of_Units__c *2)+( NewP__c *(200+ Number_of_Units__c *3))-( NewP__c  *  HomeP__c * ( Number_of_Units__c  * 3))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Indicated Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Applicants/Insureds</relationshipLabel>
    <relationshipName>Applicants_Insureds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Discount_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Discount_Value__c</fullName>
    <formula>(Indicated_Premium__c * VALUE(TEXT( Commission__c )))/100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Discount  Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Amount_Received__c</fullName>
    <formula>Invoice__r.breadwinner_qbo__Amount_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Insured__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>breadwinner_qbo__Invoice__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/QB_Invoice__c.field-meta.xml
<CustomField>
    <fullName>QB_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QB Invoice</label>
    <referenceTo>QB_Invoice__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>from Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Policy</relationshipLabel>
    <relationshipName>Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/QB_Invoice__c.object-meta.xml
<CustomObject>
    <label>QB Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QB Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QB Invoices</relationshipLabel>
    <relationshipName>QB_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Credited__c.field-meta.xml
<CustomField>
    <fullName>Amount_Credited__c</fullName>
    <description>Amount Credited will be calculated only if any Credit Memo applied to Invoice</description>
    <label>Amount Credited</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Overdue__c.field-meta.xml
<CustomField>
    <fullName>Amount_Overdue__c</fullName>
    <formula>IF( Due_Date__c &lt; TODAY(), Amount_Due__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Overdue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Amount_Received__c</fullName>
    <label>Amount Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <description>City of the Billing Address</description>
    <label>Billing City/Town</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <description>Country of Billing Address</description>
    <label>Billing Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Postal_Code__c</fullName>
    <label>Billing Postal / Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_State__c</fullName>
    <description>State of the Billing Address</description>
    <label>Billing State/Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street_Address__c</fullName>
    <label>Billing Street Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>The e-mail address where the invoice is sent</description>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Email_Status__c.field-meta.xml
<CustomField>
    <fullName>Email_Status__c</fullName>
    <description>Email status of the invoice.
Values: NotSet, NeedToSend, EmailSent</description>
    <label>Email Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Inception_Date__c.field-meta.xml
<CustomField>
    <fullName>Inception_Date__c</fullName>
    <formula>Invoice_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inception Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/QB_Company__c.field-meta.xml
<CustomField>
    <fullName>QB_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QB Company</label>
    <referenceTo>QB_Company__c</referenceTo>
    <relationshipLabel>QB Invoices</relationshipLabel>
    <relationshipName>QB_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_Line_Item__c/QB_Line_Item__c.object-meta.xml
<CustomObject>
    <label>QB Line Item</label>
    <nameField>
        <label>QB Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QB Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <description>Master of the line item</description>
    <label>Invoice</label>
    <referenceTo>QB_Invoice__c</referenceTo>
    <relationshipLabel>QB Line Items</relationshipLabel>
    <relationshipName>QB_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QB_Line_Item__c/fields/Line_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Id__c</fullName>
    <description>Line Item reference Id</description>
    <label>Line Item Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Line_Item__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>Specifies the position of the line in the collection of transaction lines.</description>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Applicant_Insured__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Insured__c</fullName>
    <label>Applicant/Insured</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Desired_Attachment_Date__c.field-meta.xml
<CustomField>
    <fullName>Desired_Attachment_Date__c</fullName>
    <label>Proposed Inception Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/createInvoiceCtrl.cls
public class createInvoiceCtrl {    
    
    
    @AuraEnabled
    public static Quote__c getBillingAddress(string qouteid) {	
        
        Quote__c quoteObj         = new Quote__c();
        try {            
            quoteObj = [select Id,Applicant_Insured__c,Amount__c	,Applicant_Insured__r.Agent_to_Bill__r.Name,Applicant_Insured__r.Name,Applicant_Insured__r.Contact_Person_First_Name__c,Applicant_Insured__r.Contact_Person_Last_Name__c,Applicant_Insured__r.Total_Discount_Value__c, Applicant_Insured__r.BillingAddress,Applicant_Insured__r.Commission__c, Applicant_Insured__r.Indicated_Premium__c,Applicant_Insured__r.Discount_Amount__c,Desired_Attachment_Date__c from Quote__c where id=: qouteid with SECURITY_ENFORCED];
        } catch (Exception e) {
            quoteObj = null;
            //throw new AuraHandledException(e.getMessage());
        }
        return quoteObj;
    }
    
    @AuraEnabled
    public static String creatingInvoiceRecord(String invoiceData, String lineItemData) {
        
        //////System.debug('Called @@'); 
        String invoiceId = '';
        String accId     = '';
        String accQBId     = '';
        String syncToken = '';
        String parentId  = '';
        //System.debug('LineItem Data ==> '+lineItemData);
        QB_Invoice__c invoiceObj = (QB_Invoice__c)System.JSON.deserializeStrict(invoiceData, QB_Invoice__c.Class);
       
        List<QB_Line_Item__c> lineItemLisTToBeInserted = (List<QB_Line_Item__c>)System.JSON.deserializeStrict(lineItemData, List<QB_Line_Item__c>.Class);
        
        ////System.debug('Data 1 '+invoiceObj);
         //System.debug('Data 2 '+lineItemLisTToBeInserted);         
        
        QB_Invoice__c selQbForName = [SELECT Id,Name from Qb_Invoice__c Order By Name Desc LIMIT 1];
        //////System.debug('name '+selQbForName.Name.substring(4));
        String namePart = selQbForName.Name.substring(4);
        Integer nameForLineItem = Integer.ValueOf(namePart)+1;
        ////System.debug('Name '+nameForLineItem);
        insert invoiceObj;
        invoiceId = invoiceObj.Id;
        
        Integer i = 1;
        for(QB_Line_Item__c qbLineIte : lineItemLisTToBeInserted){ 
            
            Integer uiqNum = Math.round((Math.random() * (90000000) + 10000000));
            
            qbLineIte.Line_Number__c         = i;
            qbLineIte.Invoice__c             = invoiceObj.Id;
            qbLineIte.Name                   = 'INV-'+nameForLineItem+'-LienItem-'+i;
            qbLineIte.Line_Item_Id__c        = uiqNum+'-INV-'+nameForLineItem+'-'+i; 
            i++;
        } 
        
        if(!lineItemLisTToBeInserted.isEmpty()){
            //////System.debug('data');
            insert lineItemLisTToBeInserted;
            ////System.debug('Data of Invoice '+invoiceObj);
            //////System.debug('Data of Line Item '+lineItemLisTToBeInserted); 
            
            //QB_Company__c curCompany = [SELECT Id FROM QB_Company__c WHERE id =: ]
            
            
            QB_Invoice__c crInvoiceData = [SELECT Id,Billing_Street_Address__c,Billing_City__c,Billing_State__c,Billing_Postal_Code__c,Billing_Country__c,Email_Status__c,Email__c,Name,Terms__c,Account__c,Account__r.Name,Account__r.Agent_to_Bill__r.Name,Due_Date__c,Invoice_Date__c,Inception_Date__c,InceptionDate__c,Amount_Received__c,Amount_Credited__c,Policy__c,Amount_Due__c,Amount_Overdue__c,Discount_Amount__c,Credit_Memo_Total_Amount__c,Statement_Memo__c,Days_Overdue__c,Total__c,Message_Displayed__c,Sales_Rep__c,(SELECT Id,Name,Rate__c,Quantity__c,Amount__c,Product_Service__c,Description__c FROM QB_Line_Items__r) FROM QB_Invoice__c WHERE id =: invoiceId];
            
            System.debug('Invoice Full Data '+crInvoiceData);
            ////System.debug('Invoice Id '+crInvoiceData.Id);
            if(invoiceId!=''){

                Account curCompany = [SELECT QB_Sync_Token__c,QB_External_Id__c,Name,QB_Parent_Id__c FROM Account WHERE id =:invoiceObj.Account__c with SECURITY_ENFORCED];
                accId      = invoiceObj.Account__c;
                accQBId    = String.valueOf(curCompany.QB_External_Id__c);
                syncToken  = curCompany.QB_Sync_Token__c;
                parentId   = String.valueOf(curCompany.QB_Parent_Id__c);



                //////System.debug('Company Data '+curCompany);
                //////System.debug('Company External Id '+curCompany.QB_External_Id__c);
                //////System.debug('Company Display Name '+curCompany.QB_Display_Name__c);

                String JsonBodyForCustomer =    '{'+
                                    '  "Job": true, '+
                                    '  "ParentRef": {'+
                                    '    "value": '+'"'+parentId+'"\n'+
                                    '  },'+
                                    '  "SyncToken": '+'"'+syncToken+'",\n'+
                                    '  "Id": '+'"'+accQBId+'",\n'+
                                    '  "sparse": true'+
                                    '} ';

                
                Integer count;
                Integer iteration;
                String JsonBody='';
                string Temp1='';
                string Temp2='';
                string Temp3='';
                String endpoint='';                
                
                Temp1 = '{\n'+         
                    '  "Line": '+'[\n';
                       
                    Temp2='';
                    count = crInvoiceData.QB_Line_Items__r.size();
                    iteration = 0;

                    String siteUrl     = BoldLegalUtils.siteHomeUrl; 
                    String commisionId = null;
                    String grossId     = null;
                    String salesTermId = null;
                  //  String paymentMethodId   = null;


                    if(siteUrl.contains('sandbox')){
                        commisionId      = BoldLegalUtils.qbComissionRecIdSand;
                        grossId          = BoldLegalUtils.qbGrossRecIdSand;
                     salesTermId         = BoldLegalUtils.qbSalesTermSand;                  
                    }else{
                        commisionId      = BoldLegalUtils.qbComissionRecIdProd;
                        grossId          = BoldLegalUtils.qbGrossRecIdProd;
                        salesTermId      = BoldLegalUtils.qbSalesTermProd;
                    }

                    for(QB_Line_Item__c orderItemIterate : crInvoiceData.QB_Line_Items__r ){
                        iteration++;
                        decimal tempDecimal = 0;
                        String serviceName = null;
                        String serviceId   = null;

                        
                        if(orderItemIterate.Product_Service__c=='Commissions'){
                            tempDecimal = orderItemIterate.Quantity__c * orderItemIterate.Rate__c;
                            serviceName = 'Comission';
                            serviceId   = commisionId;
                        }else{
                            tempDecimal = orderItemIterate.Quantity__c * orderItemIterate.Rate__c;
                            serviceName = 'Gross Premium';
                            serviceId   = grossId;
                        }
                        Temp2 =  '    {\n'+
                            '      "DetailType": ' + '"'+'SalesItemLineDetail'+'", \n'+
                            '      "Amount": '+'"'+tempDecimal+'", \n';
                                    if(orderItemIterate.Description__c != null){
                                        Temp2+='      "Description" :'+'"'+orderItemIterate.Description__c+'", \n';
                                    }                            
                            Temp2+='      "SalesItemLineDetail": {\n'+
                            '        "ItemRef": {\n'+
                            //'          "name": '+'"'+serviceName+'", \n'+
                            '          "value": '+'"'+serviceId+'"\n'+
                            '        },\n'+
                            '        "Qty": '+'"'+orderItemIterate.Quantity__c+'",\n'+
                            '        "UnitPrice": '+'"'+orderItemIterate.Rate__c+'"\n'+
                            '      }\n'+
                            '    }\n';
                        
                        if(count == 1){   Temp2=Temp2;   }else{ if(count == iteration){  Temp2=Temp2;  }else{  Temp2=Temp2+',';  }  }

                        //////System.debug('Temp2##################'+Temp2);
                        Temp1+=Temp2 ;
                    }
                    
                    Temp3 = '  ], \n'+
                        '  "Deposit": '+'"'+crInvoiceData.Amount_Credited__c+'", \n'+   
                        '  "Balance": '+'"'+crInvoiceData.Total__c+'", \n'+
                        '  "SalesTermRef": { '+
                        '    "value": '+'"'+salesTermId+'" \n'+
                        '        },\n';                 

                        if(crInvoiceData.Statement_Memo__c!=null){
                            Temp3+='  "PrivateNote": '+'"'+crInvoiceData.Statement_Memo__c+'", \n';
                        }

                        //crInvoiceData.Message_Displayed__c!='' || crInvoiceData.Message_Displayed__c!=null
                      //  if(crInvoiceData.Message_Displayed__c!=null){
                         if(false){
                             
                            String messageText = crInvoiceData.Message_Displayed__c.replaceAll('\r\n|\n|\r',' ');
                            Temp3+='  "CustomerMemo": { '+
                                   '    "value": '+'"'+messageText+'"\n'+
                                   '        },\n';
                        }

                        if(crInvoiceData.Email__c!=null){
                            Temp3+='  "BillEmail": { '+
                                   '    "Address": '+'"'+crInvoiceData.Email__c+'"\n'+
                                   '        },\n';
                        }

                        Temp3+='  "TxnDate" : '+'"'+crInvoiceData.Invoice_Date__c+'", \n'+ 
                        '  "DueDate" : '+'"'+crInvoiceData.Due_Date__c+'", \n'+ 
                        '  "CustomerRef": {\n'+
                        '    "name": '+'"'+curCompany.Name+'", \n'+      
                        '    "value": '+'"'+curCompany.QB_External_Id__c+'"\n'+
                        '  },\n';
                       
                    
                        crInvoiceData.Sales_Rep__c = crInvoiceData.Sales_Rep__c != null ? crInvoiceData.Sales_Rep__c : '';
                        Temp3+= ' "CustomField": [ '+
                          '  {'+
                          '   "DefinitionId": "1",'+
                          '     "Name": "Policy#",'+
                          '    "Type": "StringType",'+
                          '    "StringValue": '+'"'+crInvoiceData.Policy__c+'" \n'+ 
                          '   },\n';
                          
                          if(crInvoiceData.Sales_Rep__c != null || crInvoiceData.Sales_Rep__c != '' )
                          {
                        Temp3+=  '   {'+
                          '    "DefinitionId": "2",'+
                          '    "Name": "Sales Rep",'+ 
                          '    "Type": "StringType",'+
                          '    "StringValue": '+'"'+ crInvoiceData.Sales_Rep__c +'" \n'+ 
                          '   },\n';
                          }
                          Temp3+=  '   {'+
                          '   "DefinitionId": "3",'+
                          '   "Name": "Inception Date",'+
                          '   "Type": "StringType",'+
                          '   "StringValue": '+'"'+ crInvoiceData.InceptionDate__c+'" \n'+ 
                          '  }'+
                          ' ]\n';

                      
                      Temp3+=      '}' ;
                 
                    
                    JsonBody +=Temp1+Temp3;
                    //System.debug('JsonBodyOfCustomer '+JsonBodyForCustomer);
                    //System.debug('JsonBody '+JsonBody);
 
                    
                    //QB_External_API.normalMethod(JsonBodyForCustomer, accId, JsonBody, invoiceId);
                     if(!Test.isRunningTest()){
                	 
                    	QB_External_API.updateCustomer(JsonBodyForCustomer, accId);
                    	QB_External_API.createInvoiceAndSync(JsonBody,invoiceId);         
                    }
                
            }
        }
        return invoiceId;
    }
    
    @AuraEnabled
    public static Quote__c getProducerDetails(string qouteid) {
        
        Quote__c quoteObj =new Quote__c();
        try {
            quoteObj = [select Id,Applicant_Insured__c,Amount__c	,Applicant_Insured__r.Agent_to_Bill__r.Name,Applicant_Insured__r.Name,Applicant_Insured__r.Contact_Person_First_Name__c,
            Applicant_Insured__r.Contact_Person_Last_Name__c,
             Applicant_Insured__r.BillingAddress,Producer_City__c,Producer_Country__c,Producer_State_Province__c,	
             Desired_Attachment_Date__c ,Applicant_Insured__r.Physical_Street_Address__c,Producer_Street__c	,
             Applicant_Insured__r.Physical_City__c ,Applicant_Insured__r.Physical_State__c,Producer_Zip_Postal_Code__c,	Producer__r.id,
             Applicant_Insured__r.Physical_Zip_Code__c,Applicant_Insured__r.Physical_Address_2__c,Producer__r.Name,Producer__r.Agency_Name__c,
             Applicant_Insured__r.Agency__c	 ,Applicant_Insured__r.Email__c	  ,Applicant_Insured__r.Agency_Phone__c	,Producer__r.Email,Producer__r.MobilePhone	
             from Quote__c where id=: qouteid with SECURITY_ENFORCED];

        } catch (Exception e) {
            quoteObj = null;
            //throw new AuraHandledException(e.getMessage());
        }
        return quoteObj;
    }
    @AuraEnabled
    public static Account getcondominiumdetails(String applicantId){
      
        Account accObj  = new Account();
        try{
           
          accObj =  [SELECT 
          Name,Physical_Street_Address__c,Physical_City__c,
          Physical_State__c,Physical_Zip_Code__c,Physical_Address_2__c,
          Agent_to_Bill__r.Name,Agent_to_Bill__r.Agency_Name__c,
          Agent_to_Bill__r.Email,Agent_to_Bill__r.MobilePhone	
          FROM Account where id=:applicantId with SECURITY_ENFORCED];
            return accObj;
    } catch (Exception e) {
		accObj = null;        
    }
        return accObj;
  }
  
}