force-app/main/default/objects/Account/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <formula>Agent_to_Bill__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agency_Name__c.field-meta.xml
<CustomField>
    <fullName>Agency_Name__c</fullName>
    <formula>Agent_to_Bill__r.Agency_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agency Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agency_Phone__c.field-meta.xml
<CustomField>
    <fullName>Agency_Phone__c</fullName>
    <formula>Agent_to_Bill__r.Agency_Phone__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agency Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agent_Email_Application__c.field-meta.xml
<CustomField>
    <fullName>Agent_Email_Application__c</fullName>
    <label>Producer Email (Application)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agent_Phone_Application__c.field-meta.xml
<CustomField>
    <fullName>Agent_Phone_Application__c</fullName>
    <label>Producer Phone (Application)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agent_to_Bill__c.field-meta.xml
<CustomField>
    <fullName>Agent_to_Bill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <label>Commission</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Contact_Person_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_First_Name__c</fullName>
    <label>Contact Person First Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contact_Person_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Last_Name__c</fullName>
    <label>Contact Person Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <formula>Indicated_Premium__c - (Indicated_Premium__c * VALUE(TEXT( Commission__c )))/100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Indicated_Premium__c.field-meta.xml
<CustomField>
    <fullName>Indicated_Premium__c</fullName>
    <formula>199 + ( Number_of_Units__c *2)+( NewP__c *(200+ Number_of_Units__c *3))-( NewP__c  *  HomeP__c * ( Number_of_Units__c  * 3))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Indicated Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_Address_2__c.field-meta.xml
<CustomField>
    <fullName>Physical_Address_2__c</fullName>
    <label>Physical Address</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_City__c.field-meta.xml
<CustomField>
    <fullName>Physical_City__c</fullName>
    <label>Physical City</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_State__c.field-meta.xml
<CustomField>
    <fullName>Physical_State__c</fullName>
    <label>Physical State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Physical_Street_Address__c</fullName>
    <label>Physical Address 2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Physical_Zip_Code__c</fullName>
    <label>Physical Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Producer__c.field-meta.xml
<CustomField>
    <fullName>Producer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pxx</label>
    <referenceTo>Producer__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Producer_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Producer_First_Name__c</fullName>
    <label>Producer First Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Producer_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Producer_Last_Name__c</fullName>
    <label>Producer Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/QB_External_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>QB External Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/QB_Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_Parent_Id__c</fullName>
    <externalId>true</externalId>
    <label>QB_Parent_Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Discount_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Discount_Value__c</fullName>
    <formula>(Indicated_Premium__c * VALUE(TEXT( Commission__c )))/100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Discount  Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Agency__c/Agency__c.object-meta.xml
<CustomObject>
    <label>Agency</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Agency_Name__c.field-meta.xml
<CustomField>
    <fullName>Agency_Name__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agency Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Agency_Phone__c.field-meta.xml
<CustomField>
    <fullName>Agency_Phone__c</fullName>
    <formula>Account.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agency Phone1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Producer_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Producer_Last_Name__c</fullName>
    <label>Producer Last Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Producer__c/Producer__c.object-meta.xml
<CustomObject>
    <label>Old Producer</label>
    <nameField>
        <label>Producer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Old Producers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Applicant_Insured__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Insured__c</fullName>
    <label>Applicant/Insured</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Desired_Attachment_Date__c.field-meta.xml
<CustomField>
    <fullName>Desired_Attachment_Date__c</fullName>
    <label>Proposed Inception Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Producer__c.field-meta.xml
<CustomField>
    <fullName>Producer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Producer_City__c.field-meta.xml
<CustomField>
    <fullName>Producer_City__c</fullName>
    <label>Producer City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Producer_Country__c.field-meta.xml
<CustomField>
    <fullName>Producer_Country__c</fullName>
    <label>Producer Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Producer_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Producer_State_Province__c</fullName>
    <label>Producer State/Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Producer_Street__c.field-meta.xml
<CustomField>
    <fullName>Producer_Street__c</fullName>
    <label>Producer Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Producer_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Producer_Zip_Postal_Code__c</fullName>
    <label>Producer Zip/Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/createCustomerCtrl.cls
public class createCustomerCtrl {    

    private static String searchCustomerByNameReturningId(String accName){
        system.debug('Called Search Method'); 
        String qbId = '';
        if(!Test.isRunningTest()){
	        //qbId = QB_CustomerAPI.customerReadAll(accessToken, accName); 
            qbId = QB_External_API.customerReadAllNamedCredential(accName); 
            
        }
        return qbId;
    }


    @AuraEnabled
    public static String  getContacts(string accId) {
       //System.debug('accId :: '+accId);
        List<conwrapperClass> conwrapList=new List<conwrapperClass>();
        try { 
         List<Contact> conList=[SELECT  Name,Id
                                FROM Contact
                                WHERE AccountId=: accId
                                ];
            if(!conList.isEmpty()) {               
            for(Contact con:conList)   {
                conwrapperClass conwrap=new conwrapperClass(con.Name,con.Id);
                conwrapList.add(conwrap);  
            }     
        }              
         return JSON.serialize(conwrapList);} catch (Exception e) { throw new AuraHandledException(e.getMessage()); }
    }


    @AuraEnabled
    public static Quote__c getAllDetailsOfApplicant(string qouteid) {
        try { 
        return[SELECT Id,Applicant_Insured__c,Applicant_Insured__r.Name,Applicant_Insured__r.Total_Discount_Value__c, Applicant_Insured__r.QB_External_Id__c,Applicant_Insured__r.BillingAddress,Applicant_Insured__r.Commission__c, Applicant_Insured__r.Indicated_Premium__c,Applicant_Insured__r.Discount_Amount__c,Applicant_Insured__r.Producer_First_Name__c,Applicant_Insured__r.Producer_Last_Name__c,Applicant_Insured__r.Agent_Email_Application__c,Applicant_Insured__r.Agent_Phone_Application__c,
        Applicant_Insured__r.Agent_to_Bill__c,Applicant_Insured__r.Agent_to_Bill__r.id from Quote__c WHERE id=: qouteid]; } catch (Exception e) {      throw new AuraHandledException(e.getMessage()); }
    }

    
    @AuraEnabled
    public static String creatingCustomer(String customerData, String accId, String accName){
            
        try {
               
                
                String result  = null;
                String qbId    = null;
                 
                            
                    if(accId!=''){   
                        
                        if(accName!='' && accName!=null){

                            qbId = searchCustomerByNameReturningId(accName);                            
                            System.debug('Response '+qbId);
                            
                            if(qbId == '' || qbId == null){
                                System.debug('No customer find'); 
                                if(Test.isRunningTest()){
                                    qbId = '123';
                                }else{
                                    QB_External_API.createCustomerAndSync(customerData, accId); 
                                    result = accId;                 
                                }
                            }else{
                                System.debug('Customer find '+qbId);
                                result = 'Customer with this Name, already Exists. Please Try With Different Company Name'; 
                            }
                        }
	                }
                    return result;   
                } catch (Exception e) {   throw new AuraHandledException(e.getMessage());    }
    }

 

    public class conwrapperClass{
        @AuraEnabled
        public String Name;
        @AuraEnabled
        public String id;
        public conwrapperClass(String Name,String id){
       this.Name=Name;
       this.id=id;
        }
    }
    @AuraEnabled
    public static Quote__c getProducerDetails(string qouteid) {
        try {
            return[select Id,Applicant_Insured__c,Amount__c	,Applicant_Insured__r.Agent_to_Bill__r.Name,Applicant_Insured__r.Name,Applicant_Insured__r.Contact_Person_First_Name__c,
            Applicant_Insured__r.Contact_Person_Last_Name__c,Producer__r.Account.QB_External_Id__c,
             Applicant_Insured__r.BillingAddress,Producer_City__c,Producer_Country__c,Producer_State_Province__c,	
             Desired_Attachment_Date__c ,Applicant_Insured__r.Physical_Street_Address__c,Producer_Street__c	,
             Applicant_Insured__r.Physical_City__c ,Applicant_Insured__r.Physical_State__c,Producer_Zip_Postal_Code__c,Producer__r.LastName	,
             Applicant_Insured__r.Physical_Zip_Code__c,Applicant_Insured__r.Physical_Address_2__c,Producer__r.Name,Producer__r.FirstName,Producer__r.Agency_Name__c,
             Applicant_Insured__r.Agency__c	 ,Applicant_Insured__r.Email__c	  ,Applicant_Insured__r.Agency_Phone__c	,Producer__r.Email,Producer__r.MobilePhone	
             from Quote__c where id=: qouteid];

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Quote__c getAllDetails(string qouteid) {
        try {
            return[SELECT 
            Id,
            Applicant_Insured__c,
            Amount__c,
            Applicant_Insured__r.QB_Parent_Id__c,
            Applicant_Insured__r.QB_External_Id__c,
            Applicant_Insured__r.Name,
            Applicant_Insured__r.Contact_Person_First_Name__c,
            Applicant_Insured__r.Contact_Person_Last_Name__c,
            Applicant_Insured__r.BillingAddress,
            Applicant_Insured__r.Physical_Street_Address__c,
            Applicant_Insured__r.Agency__c,
            Applicant_Insured__r.Email__c,
            Applicant_Insured__r.Agency_Phone__c,
            Applicant_Insured__r.Physical_City__c,
            Applicant_Insured__r.Physical_State__c,
            Applicant_Insured__r.Physical_Zip_Code__c,
            Applicant_Insured__r.Physical_Address_2__c,
            Applicant_Insured__r.Total_Discount_Value__c,
            Applicant_Insured__r.Commission__c,
            Applicant_Insured__r.Indicated_Premium__c,
            Applicant_Insured__r.Discount_Amount__c,
            Applicant_Insured__r.Agent_Email_Application__c,
            Applicant_Insured__r.Agent_Phone_Application__c,
            Producer__r.Id,
            Producer_City__c,
            Producer_Country__c,
            Producer__r.Name,
            Producer__r.FirstName,
            Producer__r.LastName,
            Producer_State_Province__c,
            Desired_Attachment_Date__c,
            Producer_Street__c,
            Producer_Zip_Postal_Code__c,
            Producer__r.Agency_Name__c,
            Producer__r.Email,
            Producer__r.MobilePhone 
            from Quote__c 
            WHERE id=: qouteid];

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}