force-app/main/default/objects/Account/fields/Agent_to_Bill__c.field-meta.xml
<CustomField>
    <fullName>Agent_to_Bill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <formula>breadwinner_qbo__Total_Amount_Due__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <formula>Indicated_Premium__c - (Indicated_Premium__c * VALUE(TEXT( Commission__c )))/100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Applicants/Insureds</relationshipLabel>
    <relationshipName>Applicants_Insureds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/QB_External_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>QB External Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Amount_Received__c</fullName>
    <formula>Invoice__r.breadwinner_qbo__Amount_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Insured__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/QB_Invoice__c.field-meta.xml
<CustomField>
    <fullName>QB_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QB Invoice</label>
    <referenceTo>QB_Invoice__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/QB_Status_Flag__c.field-meta.xml
<CustomField>
    <fullName>QB_Status_Flag__c</fullName>
    <formula>QB_Invoice__r.QB_Status_Flag__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Flag</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CURRENT</fullName>
                <default>true</default>
                <label>CURRENT</label>
            </value>
            <value>
                <fullName>RENEWED</fullName>
            </value>
            <value>
                <fullName>NON-RENEWED</fullName>
            </value>
            <value>
                <fullName>CANCELLED - FULL REFUND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/QB_Invoice__c.object-meta.xml
<CustomObject>
    <label>QB Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QB Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QB Invoices</relationshipLabel>
    <relationshipName>QB_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Credited__c.field-meta.xml
<CustomField>
    <fullName>Amount_Credited__c</fullName>
    <description>Amount Credited will be calculated only if any Credit Memo applied to Invoice</description>
    <label>Amount Credited</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Overdue__c.field-meta.xml
<CustomField>
    <fullName>Amount_Overdue__c</fullName>
    <formula>IF( Due_Date__c &lt; TODAY(), Amount_Due__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Overdue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Amount_Received__c</fullName>
    <label>Amount Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <description>City of the Billing Address</description>
    <label>Billing City/Town</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <description>Country of Billing Address</description>
    <label>Billing Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Postal_Code__c</fullName>
    <label>Billing Postal / Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_State__c</fullName>
    <description>State of the Billing Address</description>
    <label>Billing State/Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street_Address__c</fullName>
    <label>Billing Street Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Credit_Memo_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo_Total_Amount__c</fullName>
    <label>Total Credit / Refund Amoun</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Days_Overdue__c.field-meta.xml
<CustomField>
    <fullName>Days_Overdue__c</fullName>
    <formula>IF(OR(Amount_Overdue__c == 0.00,ISBLANK(Amount_Overdue__c)) , null, TODAY() - Due_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Overdue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>The e-mail address where the invoice is sent</description>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Email_Status__c.field-meta.xml
<CustomField>
    <fullName>Email_Status__c</fullName>
    <description>Email status of the invoice.
Values: NotSet, NeedToSend, EmailSent</description>
    <label>Email Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Inception_Date__c.field-meta.xml
<CustomField>
    <fullName>Inception_Date__c</fullName>
    <formula>Invoice_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inception Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Internal_Status__c.field-meta.xml
<CustomField>
    <fullName>Internal_Status__c</fullName>
    <description>This field is to hold the Status of Invoice when the Invoice is either Voided or Deleted</description>
    <label>Internal Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/QB_External_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_External_Id__c</fullName>
    <label>QB External Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/QB_Status_Flag__c.field-meta.xml
<CustomField>
    <fullName>QB_Status_Flag__c</fullName>
    <formula>IF(
CONTAINS($User.UIThemeDisplayed, &apos;Theme4&apos;),

IF(
ISBLANK( Internal_Status__c ),
IF( OR(Status__c = &apos;Paid&apos;, Status__c = &apos;Closed&apos;),
IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/green-flag.png&quot;, &quot;Paid&quot;),
IF( Type__c = &apos;Credit Memo&apos;,
IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/yflag.png&quot;, &quot;Unapplied&quot;),
IF( Amount_Overdue__c &gt; 0,
IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/red-flag.png&quot;, &quot;Overdue&quot;) ,
IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/yflag.png&quot;, &quot;Open&quot; )
)
)
),
IF(OR(Internal_Status__c = &apos;Pending&apos;,Internal_Status__c = &apos;Open/Partial&apos;), IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/yflag.png&quot;,&quot;Open&quot;),
IF(OR(Internal_Status__c = &apos;Invoiced In Full&apos;,Internal_Status__c = &apos;Closed&apos;),IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/green-flag.png&quot;, &quot;Paid&quot;),IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/X.png&quot;, &quot;X&quot;)))
),

IF(
ISBLANK( Internal_Status__c ),
IF( OR(Status__c = &apos;Paid&apos;, Status__c = &apos;Closed&apos;),
IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Paid&quot;, 16, 16),
IF( Type__c = &apos;Credit Memo&apos;,
IMAGE(&quot;/img/samples/flag_yellow.gif&quot;, &quot;Unapplied&quot;, 16, 16),
IF( Amount_Overdue__c &gt; 0,
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;Overdue&quot;, 16, 16) ,
IMAGE(&quot;/img/samples/flag_yellow.gif&quot;, &quot;Open&quot;, 16, 16)
)
)
),
IF(OR(Internal_Status__c = &apos;Pending&apos;,Internal_Status__c = &apos;Open/Partial&apos;), IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/yflag.png&quot;, &quot;Open&quot; , 16, 16),
IF(OR(Internal_Status__c = &apos;Invoiced In Full&apos;,Internal_Status__c = &apos;Closed&apos;),IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Paid&quot;, 16, 16),IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/X.png&quot;, &quot;X&quot;, 16, 16)))
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Flag</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <label>Sales Rep</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Statement_Memo__c.field-meta.xml
<CustomField>
    <fullName>Statement_Memo__c</fullName>
    <label>Statement Memo</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
ISBLANK( Internal_Status__c ),
CASE(
Type__c,

&apos;Sales Receipt&apos;, &apos;Paid&apos;,
&apos;Refund Receipt&apos;, &apos;Paid&apos;,

&apos;Invoice&apos;, IF( Amount_Overdue__c &gt; 0,
&apos;Overdue&apos;,
IF( Amount_Due__c &gt; 0,
IF( Amount_Received__c &gt; 0,
&apos;Partial&apos;,
&apos;Open&apos;
),
&apos;Paid&apos;
)
),

IF( Credit_Memo_Unallocated_Credit__c &gt; 0,
&apos;Unapplied&apos;,
&apos;Closed&apos;
)
),
Internal_Status__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Sync_Token__c.field-meta.xml
<CustomField>
    <fullName>Sync_Token__c</fullName>
    <label>Sync Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Line_Item__c/QB_Line_Item__c.object-meta.xml
<CustomObject>
    <label>QB Line Item</label>
    <nameField>
        <label>QB Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QB Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <description>Master of the line item</description>
    <label>Invoice</label>
    <referenceTo>QB_Invoice__c</referenceTo>
    <relationshipLabel>QB Line Items</relationshipLabel>
    <relationshipName>QB_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QB_Line_Item__c/fields/Product_Service__c.field-meta.xml
<CustomField>
    <fullName>Product_Service__c</fullName>
    <description>Name of Product/Service</description>
    <label>Product/Service</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ViewInvoiceCtrl.cls
public class ViewInvoiceCtrl {
 

    @AuraEnabled(cacheable = true)
    public static String getInvoiceDetails(String invId){
        
        Integer srNo;
        String billCity = '';
        String billCountry = '';
        String billState = '';
        String billPostal = '';
        String billStreet = '';
        String emailStatus = '';
        String email = '';
        String policy = '';
        String status = '';
        String salesRep = '';
        String qbFlag = '';
        String Name = '';
        String terms = '';
        String recId = '';
        String account = '';
        String accountName = '';
        String dueDate = '';
        String invoiceDate = '';
        String inceptionDate = ''; 
        string insuredName = '';
        Decimal amountReceived;
        Decimal amountCredited;
        Decimal amountDue;
        Decimal amountOverdue;
        Decimal discountAmount;
        Decimal creditCashMemo;
        Decimal qbAmountReceive; 
        Decimal qbAmountCreited; 
        Decimal qbAmountDue; 
        Decimal qbAmountOverdue; 
        Decimal qbDiscount; 
        Decimal qbTotalAmount; 
        Decimal qbCMTotalAmount;
        Decimal qb;
        
        

        try {
            

            QB_Invoice__c  invoiceObj = [SELECT Id,Billing_Street_Address__c,Billing_City__c,InceptionDate__c,Billing_State__c,Billing_Postal_Code__c,Billing_Country__c,Email_Status__c,Email__c,Policy__c,Sales_Rep__c,Status__c,QB_Status_Flag__c,InvoiceNumber__c,Name,Terms__c,Account__c,Account__r.Name,Account__r.Agent_to_Bill__r.Name,Due_Date__c,Invoice_Date__c,Inception_Date__c,Amount_Received__c,Amount_Credited__c,Amount_Due__c,Amount_Overdue__c,Discount_Amount__c,Credit_Memo_Total_Amount__c,Statement_Memo__c,Days_Overdue__c,Total__c,(SELECT Id,Name,Rate__c,Quantity__c,Amount__c,Product_Service__c,Description__c FROM QB_Line_Items__r) FROM QB_Invoice__c WHERE Id =: invId];
 
                
                List<subWrapper> subWrapperObj = new List<subWrapper>(); 
                
                if( invoiceObj.Due_Date__c!= null){
                    Date d1 = invoiceObj.Due_Date__c ;                       
                    dueDate = DateTime.newInstance(d1.year(),d1.month(),d1.day()).format('MM/dd/YYYY');
                }
                if(invoiceObj.Invoice_Date__c != null){
                    Date d2 = invoiceObj.Invoice_Date__c;                       
                    invoiceDate = DateTime.newInstance(d2.year(),d2.month(),d2.day()).format('MM/dd/YYYY');
                }
                if(invoiceObj.InceptionDate__c!= null){
                    // Date d3 = invoiceObj.Inception_Date__c; 
                    Date d3 = invoiceObj.InceptionDate__c;                           
                    inceptionDate = DateTime.newInstance(d3.year(),d3.month(),d3.day()).format('MM/dd/YYYY');
                }
             
                if(invoiceObj.Amount_Received__c !=null){
                    qbAmountReceive = invoiceObj.Amount_Received__c.setScale(2);
                }
                if(invoiceObj.Amount_Credited__c != null){
                    qbAmountCreited= invoiceObj.Amount_Credited__c.setScale(2);
                }
                if(invoiceObj.Amount_Due__c != null){
                    qbAmountDue= invoiceObj.Amount_Due__c.setScale(2);
                }
                if(invoiceObj.Amount_Overdue__c != null){
 				    qbAmountOverdue= invoiceObj.Amount_Overdue__c.setScale(2);
                }
                if(invoiceObj.Discount_Amount__c != null){
                   qbDiscount= invoiceObj.Discount_Amount__c.setScale(2);
                }
                if(invoiceObj.Credit_Memo_Total_Amount__c != null){
                   qbCMTotalAmount= invoiceObj.Credit_Memo_Total_Amount__c.setScale(2);
                }
                if(invoiceObj.Total__c != null){
                    qbTotalAmount= invoiceObj.Total__c.setScale(2);
                 }    
            

                Integer i = 1;
                for(QB_Line_Item__c qbLineIte : invoiceObj.QB_Line_Items__r){
                    if(qbLineIte.Amount__c != null){
                        qbLineIte.Amount__c = qbLineIte.Amount__c.setScale(2);
                    }
                    if(qbLineIte.Rate__c != null){
                        qbLineIte.Rate__c = qbLineIte.Rate__c.setScale(2);
                    }

                    subWrapper subWrapperClass = new subWrapper(i, qbLineIte.Id, qbLineIte.Name, qbLineIte.Rate__c, qbLineIte.Quantity__c, qbLineIte.Amount__c, qbLineIte.Product_Service__c,
                    qbLineIte.Description__c);                                     
                    subWrapperObj.add(subWrapperClass);
                    i++;                    
                }
                	
                    mainWrapper mainWrapperClass    =  new mainWrapper(
                        invoiceObj.Days_Overdue__c,
                        invoiceObj.Statement_Memo__c,
                        invoiceObj.Id,
                        invoiceObj.Billing_Street_Address__c,
                        invoiceObj.Billing_City__c,
                        invoiceObj.Billing_State__c,
                        invoiceObj.Billing_Postal_Code__c,
                        invoiceObj.Billing_Country__c,
                        invoiceObj.Email_Status__c,
                        invoiceObj.Email__c,
                        invoiceObj.Policy__c,
                        invoiceObj.Sales_Rep__c,
                        invoiceObj.Status__c,
                        invoiceObj.QB_Status_Flag__c,
                        invoiceObj.Name,
                        invoiceObj.InvoiceNumber__c,
                        invoiceObj.Terms__c,
                        invoiceObj.Account__c,
                        invoiceObj.Account__r.Agent_to_Bill__r.Name,
                        invoiceObj.Account__r.Name,
                        dueDate,
                        invoiceDate,
                        inceptionDate,          
                        qbAmountReceive,
                        qbAmountCreited,
                        qbAmountDue,
                        qbAmountOverdue,
                        qbDiscount,
                        qbTotalAmount,
                        qbCMTotalAmount,
                        subWrapperObj);
             
            return JSON.serialize(mainWrapperClass);
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    
    public class mainWrapper{

        @AuraEnabled
        public Decimal dueDays;
        @AuraEnabled
        public String statement;
        @AuraEnabled
        public String recId;        
        @AuraEnabled
        public String billStreet;          
        @AuraEnabled
        public String billCity;        
        @AuraEnabled
        public string billState;
        @AuraEnabled
        public String billPostal;        
        @AuraEnabled
        public String billCountry;
        @AuraEnabled
        public String emailStatus;        
        @AuraEnabled
        public String email;
        @AuraEnabled
        public String policy;        
        @AuraEnabled
        public String salesRep;
        @AuraEnabled
        public String status;        
        @AuraEnabled
        public String qbFlag;
        @AuraEnabled
        public String name;    
        @AuraEnabled 
        public String invoiceName;      
        @AuraEnabled
        public String terms;    
        @AuraEnabled
        public String account;        
        @AuraEnabled
        public String accountName;
        @AuraEnabled
        public String dueDate;        
        @AuraEnabled
        public String invoiceDate;
        @AuraEnabled
        public String inceptionDate;        
        @AuraEnabled
        public String insuredName;
        @AuraEnabled
        public Decimal amountReceived;
        @AuraEnabled
        public Decimal amountCredited;        
        @AuraEnabled
        public Decimal amountDue;
        @AuraEnabled
        public Decimal amountOverdue;
        @AuraEnabled
        public Decimal discountAmount;
        @AuraEnabled
        public Decimal creditCashMemo;
        @AuraEnabled
        public Decimal totalAmount;
        @AuraEnabled   
        public String URL;
        @AuraEnabled   
        public List<subWrapper> LineItems;
        @AuraEnabled   
        public String bgClass;         
      

        public mainWrapper(Decimal dueDays, String statement, String recId, String billStreet,String  billCity,String  billState ,String billPostal ,String billCountry ,
        String emailStatus ,String email ,String policy,String salesRep,String  status,String  qbFlag,String  name,String invoiceName,String terms,String  account ,String accountName ,String insuredName ,String dueDate,String  invoiceDate ,String inceptionDate,Decimal amountReceived
        ,Decimal amountCredited,Decimal amountDue,Decimal amountOverdue ,Decimal discountAmount ,Decimal totalAmount,Decimal creditCashMemo,List<subWrapper> LineItems ){
           
            // thissrNo=srNo;
            this.dueDays   = dueDays;
            this.statement = statement;
            this.recId = recId;           
            this.billStreet=billStreet;
            this.billCity =billCity;
            this.billState= billState;
            this.billPostal=billPostal;
            this.billCountry =billCountry;
            this.emailStatus=emailStatus;
            this.email =email;
            this.policy =policy;
            this.insuredName = insuredName;
            this.salesRep =salesRep;
            this.status =status;
            this.qbFlag =qbFlag;            
            this.terms =terms;
            this.account =account;
            this.accountName= accountName;
            this.dueDate =dueDate;
            this.invoiceDate =invoiceDate;
            this.inceptionDate =inceptionDate;
            this.amountReceived =amountReceived;
            this.amountCredited = amountCredited;
            this.amountDue  =amountDue;
            this.amountOverdue=amountOverdue;
            this.discountAmount =discountAmount;
            this.creditCashMemo=creditCashMemo;
            this.totalAmount = totalAmount;
            this.URL= '/'+recId;
            this.LineItems=LineItems;
            if(invoiceName!= null){
                this.name = invoiceName;
            }else{
                this.name =name;
            }       
           
            if(status == 'Open'){
                this.bgClass = 'slds-size_2-of-3 slds-text-align_left open-class';
            }else if(status=='Overdue'){
                this.bgClass = 'slds-size_2-of-3 slds-text-align_left overdue-class';
            }else if(status=='Closed'){
                this.bgClass = 'slds-size_2-of-3 slds-text-align_left closed-class';
            }else if(status=='Paid'){
                this.bgClass = 'slds-size_2-of-3 slds-text-align_left paid-class';
            }
        }       
    }

    public class subWrapper{

        @AuraEnabled
        public Integer srNo;
        @AuraEnabled
        public String id;
        @AuraEnabled
        public String srdesc;
        @AuraEnabled
        public String linename;
        @AuraEnabled
        public Decimal rate;
        @AuraEnabled
        public Decimal quantity;
        @AuraEnabled
        public Decimal lineamount;
        @AuraEnabled
        public String productService;
        @AuraEnabled   
        public String URL;
        @AuraEnabled   
        public Boolean isCommission;
        
          public subWrapper(Integer srNo ,String id ,String linename  ,Decimal rate ,Decimal quantity  ,Decimal lineamount ,String productService, String srdesc)
          {
            this.srdesc = srdesc;
            this.srNo =srNo;
            this.id =id;
            this.linename =linename;
            this.rate =rate;
            this.quantity =quantity;
            this.lineamount =lineamount;
            this.productService = productService;
            
            if(productService == 'Commissions'){
                this.isCommission = true;
            }else{
                this.isCommission = false;
            }
            this.URL= '/'+Id;
          }
    }
    
    
    
    @AuraEnabled
    public static string generatePdf(String invId){
        try {
            PageReference PDFPage = new PageReference('/apex/PDFdownload?Id=' + invId);
            Blob pdfBlob = PDFPage.getContent();
            try{
                Policy__c policy= [SELECT Id FROM Policy__c WHERE QB_Invoice__c =:invId];
                //Attach PDF to Invoice... **Dec 6th 2022..
                if(policy!= null){
                    ContentVersion file = new ContentVersion();
                    file.Title = 'Invoice.pdf';
                    file.PathOnClient = 'Invoice.pdf';
                    file.VersionData = pdfBlob;
                    file.FirstPublishLocationId = policy.Id;
                    insert file;
                }
                String base64Pdf = EncodingUtil.base64Encode(pdfBlob);
                return base64Pdf;
                
                // System.debug('Pdf Blob'+pdfBlob);
                
            }catch(Exception e){
                // System.debug('Pdf Blob'+pdfBlob);
                String base64Pdf = EncodingUtil.base64Encode(pdfBlob);
                return base64Pdf;
            }
           
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static string generatePLPolicyPdf(String invId){
        try {
            PageReference PDFPage = new PageReference('/apex/PLPolicyVFPage?Id=' + invId);
            Blob pdfBlob = PDFPage.getContent();
            try{
                Policy__c policy= [SELECT Id,Name FROM Policy__c WHERE QB_Invoice__c =:invId];
                if(policy != null){
                    //Attach PDF to Invoice... **Dec 6th 2022..
                    ContentVersion file = new ContentVersion();
                    file.Title = 'BOLD PL Policy'+policy.Name+'.pdf';
                    file.PathOnClient =  'BOLD PL Policy'+policy.Name+'.pdf';
                    file.VersionData = pdfBlob;
                    file.FirstPublishLocationId = policy.Id;
                    insert file;
                    
                }
                String base64Pdf = EncodingUtil.base64Encode(pdfBlob);
                return base64Pdf;
            }catch(Exception e){
                // System.debug('Pdf Blob'+pdfBlob);
                String base64Pdf = EncodingUtil.base64Encode(pdfBlob);
                return base64Pdf;
            }
           
           
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static string UpdateQB(String invId){
        String result='Initial';
        String siteUrl     = BoldLegalUtils.siteHomeUrl;
        String commisionId = null;
        String grossId     = null;
        String salesTermId = null;
        List<QB_Line_Item__c> qbToUpdate=new List<QB_Line_Item__c>();
        List<QB_Invoice__c> invToUpdate=new List<QB_Invoice__c>();
        List<QB_Invoice__c>  invoiceObj = [SELECT Id,Statement_Memo__c,Discount_Amount__c,Credit_Memo_Total_Amount__c,Amount_Due__c,Amount_Overdue__c,Status__c,Total__c,
        Amount_Received__c,Amount_Credited__c,Internal_Status__c,Sync_Token__c,Due_Date__c,
        QB_External_Id__c,InvoiceNumber__c,Account__r.QB_External_Id__c,Account__r.Name,
        (SELECT Id,Name,Rate__c,Quantity__c,Amount__c,Product_Service__c,Description__c FROM QB_Line_Items__r) FROM QB_Invoice__c WHERE Id=: invId];
        String JSON ='';
        if(siteUrl.contains('sandbox')){
            commisionId      = BoldLegalUtils.qbComissionRecIdSand;
            grossId          = BoldLegalUtils.qbGrossRecIdSand;
            salesTermId         = BoldLegalUtils.qbSalesTermSand;
        }else{
            commisionId      = BoldLegalUtils.qbComissionRecIdProd;
            grossId          = BoldLegalUtils.qbGrossRecIdProd;
            salesTermId      = BoldLegalUtils.qbSalesTermProd;
        }
        for(QB_Invoice__c qbItr:invoiceObj )
        {
            JSON += '{  "sparse": true,\n'+
           ' "Id": '+'"'+qbItr.QB_External_Id__c+'",\n'+
           ' "SyncToken": '+'"'+qbItr.Sync_Token__c+'"\n'+
           '} ';
            qbItr.Internal_Status__c='Voided';
            qbItr.Total__c=0.00;
            qbItr.Statement_Memo__c='Voided';  
            qbItr.Amount_Due__c=0.00;
            qbItr.Credit_Memo_Total_Amount__c=0.00;
            qbItr.Discount_Amount__c=0.00;
            qbItr.Amount_Received__c=0.00;
            qbItr.Amount_Credited__c=0.00;
            invToUpdate.add(qbItr);          
            for(QB_Line_Item__c itemsItr:qbItr.QB_Line_Items__r ){
                itemsItr.Quantity__c=0.00;
                itemsItr.Amount__c=0.00;
                itemsItr.Rate__c=0.00;
                itemsItr.Description__c='';
                // String serviceName = null;
                // String serviceId   = null;
                // if(itemsItr.Product_Service__c=='Commissions'){
                //     // tempDecimal = itemsItr.Quantity__c * itemsItr.Rate__c;
                //     serviceName = 'Comission';
                //     serviceId   = commisionId;
                // }else{
                //     // tempDecimal = itemsItr.Quantity__c * itemsItr.Rate__c;
                //     serviceName = 'Gross Premium';
                //     serviceId   = grossId;
                // }
                // qbToUpdate.add( itemsItr);

            }
        }
        System.debug('Void Invoice Data: '+JSON);
        QB_External_API.updateInvoice(JSON);
        update qbToUpdate;
        update invToUpdate;
        result='Success';
        return result;
    }

}