force-app/main/default/objects/Account/fields/Agent_to_Bill__c.field-meta.xml
<CustomField>
    <fullName>Agent_to_Bill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <formula>breadwinner_qbo__Total_Amount_Due__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <formula>Indicated_Premium__c - (Indicated_Premium__c * VALUE(TEXT( Commission__c )))/100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Applicants/Insureds</relationshipLabel>
    <relationshipName>Applicants_Insureds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Amount_Received__c</fullName>
    <formula>Invoice__r.breadwinner_qbo__Amount_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Insured__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>breadwinner_qbo__Invoice__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/QB_Invoice__c.field-meta.xml
<CustomField>
    <fullName>QB_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QB Invoice</label>
    <referenceTo>QB_Invoice__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/QB_Status_Flag__c.field-meta.xml
<CustomField>
    <fullName>QB_Status_Flag__c</fullName>
    <formula>QB_Invoice__r.QB_Status_Flag__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Flag</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CURRENT</fullName>
                <default>true</default>
                <label>CURRENT</label>
            </value>
            <value>
                <fullName>RENEWED</fullName>
            </value>
            <value>
                <fullName>NON-RENEWED</fullName>
            </value>
            <value>
                <fullName>CANCELLED - FULL REFUND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/QB_Invoice__c.object-meta.xml
<CustomObject>
    <label>QB Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QB Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QB Invoices</relationshipLabel>
    <relationshipName>QB_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Credited__c.field-meta.xml
<CustomField>
    <fullName>Amount_Credited__c</fullName>
    <description>Amount Credited will be calculated only if any Credit Memo applied to Invoice</description>
    <label>Amount Credited</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Overdue__c.field-meta.xml
<CustomField>
    <fullName>Amount_Overdue__c</fullName>
    <formula>IF( Due_Date__c &lt; TODAY(), Amount_Due__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Overdue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Amount_Received__c</fullName>
    <label>Amount Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <description>City of the Billing Address</description>
    <label>Billing City/Town</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <description>Country of Billing Address</description>
    <label>Billing Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Postal_Code__c</fullName>
    <label>Billing Postal / Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_State__c</fullName>
    <description>State of the Billing Address</description>
    <label>Billing State/Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Billing_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street_Address__c</fullName>
    <label>Billing Street Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Credit_Memo_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo_Total_Amount__c</fullName>
    <label>Total Credit / Refund Amoun</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Days_Overdue__c.field-meta.xml
<CustomField>
    <fullName>Days_Overdue__c</fullName>
    <formula>IF(OR(Amount_Overdue__c == 0.00,ISBLANK(Amount_Overdue__c)) , null, TODAY() - Due_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Overdue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>The e-mail address where the invoice is sent</description>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Email_Status__c.field-meta.xml
<CustomField>
    <fullName>Email_Status__c</fullName>
    <description>Email status of the invoice.
Values: NotSet, NeedToSend, EmailSent</description>
    <label>Email Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Inception_Date__c.field-meta.xml
<CustomField>
    <fullName>Inception_Date__c</fullName>
    <formula>Invoice_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inception Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/QB_Status_Flag__c.field-meta.xml
<CustomField>
    <fullName>QB_Status_Flag__c</fullName>
    <formula>IF(
CONTAINS($User.UIThemeDisplayed, &apos;Theme4&apos;),

IF(
ISBLANK( Internal_Status__c ),
IF( OR(Status__c = &apos;Paid&apos;, Status__c = &apos;Closed&apos;),
IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/green-flag.png&quot;, &quot;Paid&quot;),
IF( Type__c = &apos;Credit Memo&apos;,
IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/yflag.png&quot;, &quot;Unapplied&quot;),
IF( Amount_Overdue__c &gt; 0,
IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/red-flag.png&quot;, &quot;Overdue&quot;) ,
IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/yflag.png&quot;, &quot;Open&quot; )
)
)
),
IF(OR(Internal_Status__c = &apos;Pending&apos;,Internal_Status__c = &apos;Open/Partial&apos;), IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/yflag.png&quot;,&quot;Open&quot;),
IF(OR(Internal_Status__c = &apos;Invoiced In Full&apos;,Internal_Status__c = &apos;Closed&apos;),IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/green-flag.png&quot;, &quot;Paid&quot;),IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/X.png&quot;, &quot;X&quot;)))
),

IF(
ISBLANK( Internal_Status__c ),
IF( OR(Status__c = &apos;Paid&apos;, Status__c = &apos;Closed&apos;),
IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Paid&quot;, 16, 16),
IF( Type__c = &apos;Credit Memo&apos;,
IMAGE(&quot;/img/samples/flag_yellow.gif&quot;, &quot;Unapplied&quot;, 16, 16),
IF( Amount_Overdue__c &gt; 0,
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;Overdue&quot;, 16, 16) ,
IMAGE(&quot;/img/samples/flag_yellow.gif&quot;, &quot;Open&quot;, 16, 16)
)
)
),
IF(OR(Internal_Status__c = &apos;Pending&apos;,Internal_Status__c = &apos;Open/Partial&apos;), IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/yflag.png&quot;, &quot;Open&quot; , 16, 16),
IF(OR(Internal_Status__c = &apos;Invoiced In Full&apos;,Internal_Status__c = &apos;Closed&apos;),IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Paid&quot;, 16, 16),IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/X.png&quot;, &quot;X&quot;, 16, 16)))
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Flag</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <label>Sales Rep</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Statement_Memo__c.field-meta.xml
<CustomField>
    <fullName>Statement_Memo__c</fullName>
    <label>Statement Memo</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
ISBLANK( Internal_Status__c ),
CASE(
Type__c,

&apos;Sales Receipt&apos;, &apos;Paid&apos;,
&apos;Refund Receipt&apos;, &apos;Paid&apos;,

&apos;Invoice&apos;, IF( Amount_Overdue__c &gt; 0,
&apos;Overdue&apos;,
IF( Amount_Due__c &gt; 0,
IF( Amount_Received__c &gt; 0,
&apos;Partial&apos;,
&apos;Open&apos;
),
&apos;Paid&apos;
)
),

IF( Credit_Memo_Unallocated_Credit__c &gt; 0,
&apos;Unapplied&apos;,
&apos;Closed&apos;
)
),
Internal_Status__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Line_Item__c/QB_Line_Item__c.object-meta.xml
<CustomObject>
    <label>QB Line Item</label>
    <nameField>
        <label>QB Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QB Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <description>Master of the line item</description>
    <label>Invoice</label>
    <referenceTo>QB_Invoice__c</referenceTo>
    <relationshipLabel>QB Line Items</relationshipLabel>
    <relationshipName>QB_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QB_Line_Item__c/fields/Product_Service__c.field-meta.xml
<CustomField>
    <fullName>Product_Service__c</fullName>
    <description>Name of Product/Service</description>
    <label>Product/Service</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ViewInvoiceCtrl_Test.cls
@isTest
public class ViewInvoiceCtrl_Test {
    @isTest static void myTest() {
        
        Test.startTest();
     
        QB_Invoice__c invoice          = new QB_Invoice__c();
        invoice.Policy__c              = '20222611D';
        invoice.Due_Date__c            = Date.newInstance(2022, 12, 9);
        invoice.Invoice_Date__c        = Date.newInstance(2022, 11, 9);
        invoice.Amount_Received__c     = 1000;
        invoice.Amount_Credited__c     = 1000;
        invoice.Discount_Amount__c     = 1000;
        invoice.Amount_Due__c          = 1000;
        invoice.Credit_Memo_Total_Amount__c     = 1000;
        invoice.Total__c     = 1000;        
        insert invoice;
        
        QB_Line_Item__c  lineitem  = new QB_Line_Item__c();
        lineitem.Amount__c         = 1000;
        lineitem.Rate__c           = 10;
        lineitem.Invoice__c        = invoice.id;
        insert lineitem;
        
        QB_Invoice__c  invoiceObj = [SELECT Id,Billing_Street_Address__c,Billing_City__c,Billing_State__c,Billing_Postal_Code__c,Billing_Country__c,Email_Status__c,Email__c,Policy__c,Sales_Rep__c,Status__c,QB_Status_Flag__c,Name,Terms__c,Account__c,Account__r.Name,Account__r.Agent_to_Bill__r.Name,Due_Date__c,Invoice_Date__c,Inception_Date__c,Amount_Received__c,Amount_Credited__c,Amount_Due__c,Amount_Overdue__c,Discount_Amount__c,Credit_Memo_Total_Amount__c,Statement_Memo__c,Days_Overdue__c,Total__c,(SELECT Id,Name,Rate__c,Quantity__c,Amount__c,Product_Service__c,Description__c FROM QB_Line_Items__r) FROM QB_Invoice__c WHERE Id =: invoice.id];
        
        ViewInvoiceCtrl.getInvoiceDetails(invoiceObj.id);
        //ViewInvoiceCtrl.generatePdf(invoice.id);
      
        Test.stopTest();
        
    }
    
    @isTest static void myTest2() {
        Test.startTest();
        QB_Invoice__c invoice          = new QB_Invoice__c();
        invoice.Policy__c              = '20222611D';
        invoice.Due_Date__c            = Date.newInstance(2022, 12, 9);
        invoice.Invoice_Date__c        = Date.newInstance(2022, 11, 9);
        invoice.Amount_Received__c     = 1000;
        invoice.Amount_Credited__c     = 1000;
        invoice.Discount_Amount__c     = 1000;
        invoice.Amount_Due__c          = 1000;
        invoice.Credit_Memo_Total_Amount__c     = 1000;
        invoice.Total__c     = 1000;
        insert invoice;
        
        QB_Line_Item__c  lineitem  = new QB_Line_Item__c();
        lineitem.Amount__c         = 1000;
        lineitem.Rate__c           = 10;
        lineitem.Invoice__c        = invoice.id;
        insert lineitem;
        
        QB_Invoice__c  invoiceObj = [SELECT Id,Billing_Street_Address__c,Billing_City__c,Billing_State__c,Billing_Postal_Code__c,Billing_Country__c,Email_Status__c,Email__c,Policy__c,Sales_Rep__c,Status__c,QB_Status_Flag__c,Name,Terms__c,Account__c,Account__r.Name,Account__r.Agent_to_Bill__r.Name,Due_Date__c,Invoice_Date__c,Inception_Date__c,Amount_Received__c,Amount_Credited__c,Amount_Due__c,Amount_Overdue__c,Discount_Amount__c,Credit_Memo_Total_Amount__c,Statement_Memo__c,Days_Overdue__c,Total__c,(SELECT Id,Name,Rate__c,Quantity__c,Amount__c,Product_Service__c,Description__c FROM QB_Line_Items__r) FROM QB_Invoice__c WHERE Id =: invoice.id];
        
        
        ViewInvoiceCtrl.UpdateQB(invoiceObj.id);
        Test.stopTest();
        
    }
    
    
  
}