force-app/main/default/objects/Account/fields/Agent_Email_Application__c.field-meta.xml
<CustomField>
    <fullName>Agent_Email_Application__c</fullName>
    <label>Producer Email (Application)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agent_Phone_Application__c.field-meta.xml
<CustomField>
    <fullName>Agent_Phone_Application__c</fullName>
    <label>Producer Phone (Application)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Producer_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Producer_First_Name__c</fullName>
    <label>Producer First Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Producer_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Producer_Last_Name__c</fullName>
    <label>Producer Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/QB_External_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>QB External Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/QB_Sync_Token__c.field-meta.xml
<CustomField>
    <fullName>QB_Sync_Token__c</fullName>
    <label>QB Sync Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/QB_Company__c.object-meta.xml
<CustomObject>
    <description>The QuickBooks Company (aka BAC) is a perfect copy of your QuickBooks Customer</description>
    <label>QB Company</label>
    <nameField>
        <displayFormat>BW - {0000}</displayFormat>
        <label>QuickBooks Company #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QB Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Company__c/fields/QB_City__c.field-meta.xml
<CustomField>
    <fullName>QB_City__c</fullName>
    <label>Town / City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>QB_Company_Name__c</fullName>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Country__c.field-meta.xml
<CustomField>
    <fullName>QB_Country__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>QB_Display_Name__c</fullName>
    <label>Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Email__c.field-meta.xml
<CustomField>
    <fullName>QB_Email__c</fullName>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_External_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_External_Id__c</fullName>
    <label>QB External Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Family_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>QB_Family_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Given_First_Name__c.field-meta.xml
<CustomField>
    <fullName>QB_Given_First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>QB_Postal_Code__c</fullName>
    <label>Postal / Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Region__c.field-meta.xml
<CustomField>
    <fullName>QB_Region__c</fullName>
    <label>State / Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Salesforce_Account__c.field-meta.xml
<CustomField>
    <fullName>QB_Salesforce_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesforce Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliated QuickBooks Companies</relationshipLabel>
    <relationshipName>QBO_Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>QB_Street_Address__c</fullName>
    <label>Street Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/QB_Company__c/fields/QB_Sync_Token__c.field-meta.xml
<CustomField>
    <fullName>QB_Sync_Token__c</fullName>
    <label>Sync Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EditCustomerCtrl.cls
public with sharing class EditCustomerCtrl {
    public EditCustomerCtrl() {

    }
    @AuraEnabled
    public static QB_Company__c getAllDetailsOfApplicant(string qouteid) {
        try { 

        return[SELECT 
        QB_Salesforce_Account__r.BillingAddress,
        QB_Salesforce_Account__r.Agent_Phone_Application__c,
        QB_Salesforce_Account__r.Agent_Email_Application__c,
        QB_Salesforce_Account__r.Producer_Last_Name__c,
        QB_Salesforce_Account__c,
        QB_Salesforce_Account__r.Name,
        QB_Salesforce_Account__r.Producer_First_Name__c ,
        QB_Given_First_Name__c,
        QB_Family_Last_Name__c,
        QB_Company_Name__c,QB_Email__c,
        QB_Street_Address__c,QB_City__c	,QB_Country__c,
        QB_Postal_Code__c,QB_Region__c	
        FROM QB_Company__c
        WHERE id=: qouteid];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static String UpdateCustomer(String companyData){
        try {
                // System.debug('Applicant Id '+accId);
                // System.debug('Customer Data '+customerData);
                
                String result  = 'error';
                String comName = 'Company Name';
                QB_Company__c comObj  = (QB_Company__c)System.JSON.deserializeStrict(companyData, QB_Company__c.Class);
                comName = comObj.QB_Display_Name__c;

               // List<QB_Company__c> comList = [SELECT Id FROM QB_Company__c WHERE QB_Display_Name__c =: comName];
               // if(comList.isEmpty()){
                //     System.debug('comObj Id '+comObj.Id);                    
                //     if(comName!=''){

                //         if(!Test.isRunningTest()){
                //             QB_External_API.createCustomerAndSync(customerData, comName);
                //         }
                //         QB_Company__c comDetails = [Select Id,Name, QB_External_ID__c,QB_Sync_Token__c From QB_Company__c Where Id = :comObj.Id ];
                //                     System.debug('Account Data '+comDetails.Name+' Account Customer ID '+comDetails.QB_External_ID__c);
                //         if (string.isBlank(comDetails.QB_External_ID__c) || comDetails.QB_External_ID__c == null ){
                //             result = 'error';
                //         }else{
                //             result = 'success';  
                //         }
                //     }
                // }else{
                //     result = 'Company with this Name, already Exists. Please Try With Different Display Name';
                // }
                Database.SaveResult srList = Database.update(comObj, false);
                    if (srList.isSuccess()) {
                        result = 'success';  
                    }else{
                        result = 'error';
                    }
                  
                               
                return result;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}