force-app/main/default/objects/Account/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <formula>Agent_to_Bill__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <formula>breadwinner_qbo__Total_Amount_Due__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <formula>Indicated_Premium__c - (Indicated_Premium__c * VALUE(TEXT( Commission__c )))/100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Agency__c/Agency__c.object-meta.xml
<CustomObject>
    <label>Agency</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Invoice__c/QB_Invoice__c.object-meta.xml
<CustomObject>
    <label>QB Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QB Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QB Invoices</relationshipLabel>
    <relationshipName>QB_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <formula>Account__r.Agency_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Credited__c.field-meta.xml
<CustomField>
    <fullName>Amount_Credited__c</fullName>
    <description>Amount Credited will be calculated only if any Credit Memo applied to Invoice</description>
    <label>Amount Credited</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Overdue__c.field-meta.xml
<CustomField>
    <fullName>Amount_Overdue__c</fullName>
    <formula>IF( Due_Date__c &lt; TODAY(), Amount_Due__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Overdue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Amount_Received__c</fullName>
    <label>Amount Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Credit_Memo_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo_Total_Amount__c</fullName>
    <label>Total Credit / Refund Amoun</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Inception_Date__c.field-meta.xml
<CustomField>
    <fullName>Inception_Date__c</fullName>
    <formula>Invoice_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inception Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/QB_Status_Flag__c.field-meta.xml
<CustomField>
    <fullName>QB_Status_Flag__c</fullName>
    <formula>IF(
CONTAINS($User.UIThemeDisplayed, &apos;Theme4&apos;),

IF(
ISBLANK( Internal_Status__c ),
IF( OR(Status__c = &apos;Paid&apos;, Status__c = &apos;Closed&apos;),
IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/green-flag.png&quot;, &quot;Paid&quot;),
IF( Type__c = &apos;Credit Memo&apos;,
IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/yflag.png&quot;, &quot;Unapplied&quot;),
IF( Amount_Overdue__c &gt; 0,
IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/red-flag.png&quot;, &quot;Overdue&quot;) ,
IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/yflag.png&quot;, &quot;Open&quot; )
)
)
),
IF(OR(Internal_Status__c = &apos;Pending&apos;,Internal_Status__c = &apos;Open/Partial&apos;), IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/yflag.png&quot;,&quot;Open&quot;),
IF(OR(Internal_Status__c = &apos;Invoiced In Full&apos;,Internal_Status__c = &apos;Closed&apos;),IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/green-flag.png&quot;, &quot;Paid&quot;),IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/X.png&quot;, &quot;X&quot;)))
),

IF(
ISBLANK( Internal_Status__c ),
IF( OR(Status__c = &apos;Paid&apos;, Status__c = &apos;Closed&apos;),
IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Paid&quot;, 16, 16),
IF( Type__c = &apos;Credit Memo&apos;,
IMAGE(&quot;/img/samples/flag_yellow.gif&quot;, &quot;Unapplied&quot;, 16, 16),
IF( Amount_Overdue__c &gt; 0,
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;Overdue&quot;, 16, 16) ,
IMAGE(&quot;/img/samples/flag_yellow.gif&quot;, &quot;Open&quot;, 16, 16)
)
)
),
IF(OR(Internal_Status__c = &apos;Pending&apos;,Internal_Status__c = &apos;Open/Partial&apos;), IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/yflag.png&quot;, &quot;Open&quot; , 16, 16),
IF(OR(Internal_Status__c = &apos;Invoiced In Full&apos;,Internal_Status__c = &apos;Closed&apos;),IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Paid&quot;, 16, 16),IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/X.png&quot;, &quot;X&quot;, 16, 16)))
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Flag</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
ISBLANK( Internal_Status__c ),
CASE(
Type__c,

&apos;Sales Receipt&apos;, &apos;Paid&apos;,
&apos;Refund Receipt&apos;, &apos;Paid&apos;,

&apos;Invoice&apos;, IF( Amount_Overdue__c &gt; 0,
&apos;Overdue&apos;,
IF( Amount_Due__c &gt; 0,
IF( Amount_Received__c &gt; 0,
&apos;Partial&apos;,
&apos;Open&apos;
),
&apos;Paid&apos;
)
),

IF( Credit_Memo_Unallocated_Credit__c &gt; 0,
&apos;Unapplied&apos;,
&apos;Closed&apos;
)
),
Internal_Status__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ShowInvoiceList.cls
public class InvoiceListCtrl {

    @AuraEnabled
    public static String getDataByFilter(String searchKey) {
        
        ReturnWrapper ret   = new ReturnWrapper();
        List<wrapperInv> warpperList = new List<wrapperInv>();
        List<QB_Invoice__c> invList = new List<QB_Invoice__c>();
       //System.debug('KEy  '+searchKey);
        if(searchKey != null && searchKey !=''){
            String key = '%'+ searchKey +'%'; 
            invList =  [SELECT Id,Agency__c,InvoiceNumber__c,Status__c,QB_Status_Flag__c,Name,Terms__c,Account__c,Account__r.Name,Due_Date__c,Invoice_Date__c,Inception_Date__c,Amount_Received__c,Amount_Credited__c,Amount_Due__c,Amount_Overdue__c,Discount_Amount__c,Credit_Memo_Total_Amount__c,Total__c FROM QB_Invoice__c WHERE Agency__c!='' AND (Name LIKE : key  OR InvoiceNumber__c LIKE : key) ORDER BY Name DESC]; 
        }else{
            invList =  [SELECT Id,Agency__c,InvoiceNumber__c,Status__c,QB_Status_Flag__c,Name,Terms__c,Account__c,Account__r.Name,Due_Date__c,Invoice_Date__c,Inception_Date__c,Amount_Received__c,Amount_Credited__c,Amount_Due__c,Amount_Overdue__c,Discount_Amount__c,Credit_Memo_Total_Amount__c,Total__c FROM QB_Invoice__c WHERE Agency__c!='' AND Account__c!=''  ORDER BY Name DESC];
        }

        String countQuery  = 'SELECT count() FROM  QB_Invoice__c WHERE Agency__c!= null AND Account__c!=null AND (Name LIKE : key  OR InvoiceNumber__c LIKE : key)'; 
        ret.totalRecords   = Database.countQuery(countQuery); 
        
        system.debug('key '+searchKey);
        system.debug('countQuery '+countQuery);
       //System.debug('List '+invList);
       if(!invList.isEmpty()){
        Integer i = 1;
        for(QB_Invoice__c invIte : invList){  
            wrapperInv wraObj = new wrapperInv(
                i,
                invIte.Agency__c,
                invIte.InvoiceNumber__c,
                invIte.Id,
                invIte.Status__c,
                invIte.QB_Status_Flag__c,
                invIte.Name,
                invIte.Terms__c,
                invIte.Account__c,
                invIte.Account__r.Name,
                invIte.Due_Date__c,
                invIte.Invoice_Date__c,
                invIte.Inception_Date__c,
                invIte.Amount_Received__c,
                invIte.Amount_Credited__c,
                invIte.Amount_Due__c,
                invIte.Amount_Overdue__c,
                invIte.Discount_Amount__c,
                invIte.Credit_Memo_Total_Amount__c,
                invIte.Total__c
                ); 
            warpperList.add(wraObj); 
            i++; 
        }  

            ret.records        = warpperList;
            ret.status         = 'success';

        }else{
            ret.totalRecords   = 0;
            ret.records        = null;
            ret.status         = 'success';
        }   

        return JSON.serialize(ret);
    }


    @AuraEnabled(cacheable = true)
    public static String getInvoicesList(
        Integer pageNumber,
        String lastRecordId,
        Integer recordSize, 
        String actionType,
        Boolean needQuery, 
        String orderBy
        )
    {           
       
        ReturnWrapper ret   = new ReturnWrapper();
        List<wrapperInv> wrapperList = new List<wrapperInv>();

        try {
              // get loggedIn user Detials      
                String invIteectName   = 'QB_Invoice__c';    
                Decimal conLastId   = null;
                Boolean isClosed    = false;   
                Date  filterForCloseDate  = null;

    
                String query        = 'SELECT Id,Agency__c,InvoiceNumber__c,Status__c,QB_Status_Flag__c,Name,Terms__c,Account__c,Account__r.Name,Due_Date__c,Invoice_Date__c,Inception_Date__c,Amount_Received__c,Amount_Credited__c,Amount_Due__c,Amount_Overdue__c,Discount_Amount__c,Credit_Memo_Total_Amount__c,Total__c FROM QB_Invoice__c WHERE Agency__c!= null AND Account__c!=null';
              
                        
                if(actionType == 'DESC'){
                    query+=' ORDER BY ' + orderBy + ' DESC';
                }else{
                    query+=' ORDER BY ' + orderBy + ' DESC';
                }
            
            List<QB_Invoice__c> invList =  Database.query(query);                
           
            String countQuery  = 'SELECT count() FROM  QB_Invoice__c WHERE Agency__c!= null AND Account__c!=null'; 
            ret.totalRecords   = Database.countQuery(countQuery); 
            
            
            if(!invList.isEmpty()){
                Integer i = 1;
                for(QB_Invoice__c invIte : invList){  
                    wrapperInv wraObj = new wrapperInv(
                        i,
                        invIte.Agency__c,
                        invIte.InvoiceNumber__c,
                        invIte.Id,
                        invIte.Status__c,
                        invIte.QB_Status_Flag__c,
                        invIte.Name,
                        invIte.Terms__c,
                        invIte.Account__c,
                        invIte.Account__r.Name,
                        invIte.Due_Date__c,
                        invIte.Invoice_Date__c,
                        invIte.Inception_Date__c,
                        invIte.Amount_Received__c,
                        invIte.Amount_Credited__c,
                        invIte.Amount_Due__c,
                        invIte.Amount_Overdue__c,
                        invIte.Discount_Amount__c,
                        invIte.Credit_Memo_Total_Amount__c,
                        invIte.Total__c
                        ); 
                    wrapperList.add(wraObj); 
                    i++; 
                }  

                ret.records        = wrapperList;
                ret.status         = 'success';

            }else{
                ret.records        = null;
                ret.status         = 'success';
            }   
        
        return JSON.serialize(ret);

    } catch (Exception e) {
        
            ret.totalRecords   = 0;
            ret.records        = null;
            ret.status         = 'success';
            return JSON.serialize(ret);
    }
    
}
    public class wrapperInv{
        @AuraEnabled   
        public Integer SrNo;
        @AuraEnabled   
        public String  AgencyName;
        @AuraEnabled   
        public String shortAgencyName;
        @AuraEnabled   
        public String  Id;
        @AuraEnabled   
        public String  Status;
        @AuraEnabled   
        public String  Flag;
        @AuraEnabled   
        public String  Name;
        @AuraEnabled   
        public String shortName;
        @AuraEnabled   
        public String  Term;
        @AuraEnabled   
        public String  Account;
        @AuraEnabled   
        public String  AccountName;
        @AuraEnabled   
        public String  DueDate;
        @AuraEnabled   
        public String  InvoiceDate;
        @AuraEnabled   
        public String  InceptionDate;
        @AuraEnabled   
        public Decimal  AmtReceived;
        @AuraEnabled   
        public Decimal  AmtCredit;
        @AuraEnabled   
        public Decimal  AmtDue;
        @AuraEnabled   
        public Decimal  AmtOverDue;
        @AuraEnabled   
        public Decimal  AmtDis;
        @AuraEnabled   
        public Decimal  AmtTotal;
        @AuraEnabled   
        public Decimal  CreditTotal;
        @AuraEnabled
        public String urlaccount;
        @AuraEnabled   
        public List<String> FlagArray; 

        public wrapperInv(Integer SrNo,String AgencyName,String invoiceNumber,String  Id,String  Status,String  Flag,String  Name,String  Term,String  Account,String  AccountName,Date  DueDate,Date  InvoiceDate,Date  InceptionDate,Decimal  AmtReceived,Decimal  AmtCredit,Decimal  AmtDue,Decimal  AmtOverDue,Decimal  AmtDis,Decimal  CreditTotal,Decimal  AmtTotal ){
            this.SrNo   = SrNo;
            this.AgencyName = AgencyName;
            this.Id     = Id;
            this.Status = Status;
            // if(this.Status == 'Overdue'){
            //     this.Flag = '/resource/1671476878000/StatusImages/StatusImages/red-flag.png';
            // }else if(this.Status == 'Open'){
            //     this.Flag = '/resource/1671476878000/StatusImages/StatusImages/yflag.png';
            // }else if(this.Status == 'Voided'){
            //     this.Flag = '/resource/1671476878000/StatusImages/StatusImages/X.png';
            // }else if(this.Status == 'Closed'){
            //     this.Flag = '/resource/1671476878000/StatusImages/StatusImages/green-flag.png';
            // }
            this.FlagArray   = Flag.split('"');
            this.Flag   = this.FlagArray[1];
            if(invoiceNumber!=null){
                 this.Name   = invoiceNumber;
            }else{
                this.Name   = Name; 
            }
           
            this.Term   = Term;
            this.Account = Account;
            this.AccountName = AccountName; 
            this.urlaccount = '/'+Account;
            this.shortName            = AccountName.abbreviate(13);          
            this.shortAgencyName      = AgencyName.abbreviate(13); 
            if( InvoiceDate!= null){  Date d1 = InvoiceDate ;  this.InvoiceDate = DateTime.newInstance(d1.year(),d1.month(),d1.day()).format('MM/dd/YYYY'); }else{  this.InvoiceDate = null; }
			if(InceptionDate != null){ Date d2 = InceptionDate;   this.InceptionDate = DateTime.newInstance(d2.year(),d2.month(),d2.day()).format('MM/dd/YYYY'); }else{ this.InceptionDate = null; }
            if(DueDate!= null){ Date d3 = DueDate; this.DueDate = DateTime.newInstance(d3.year(),d3.month(),d3.day()).format('MM/dd/YYYY'); }else{ this.DueDate = null; }
			if(AmtReceived != null){ this.AmtReceived = AmtReceived.setScale(2); }else{ this.AmtReceived = 0.00; }
            if(AmtCredit != null){ this.AmtCredit = AmtCredit.setScale(2); }else{ this.AmtCredit = 0.00; }
            if(AmtOverDue != null){ this.AmtOverDue = AmtOverDue.setScale(2); }else{ this.AmtOverDue = 0.00; }
            if(AmtDue != null){  this.AmtDue = AmtDue.setScale(2); }else{  this.AmtDue = 0.00; }
            if(AmtTotal != null){ this.AmtTotal = AmtTotal.setScale(2); }else{ this.AmtTotal = 0.00;}
            if(CreditTotal != null){ this.CreditTotal = CreditTotal.setScale(2); }else{  this.CreditTotal = 0.00;}
			if(AmtDis != null){ this.AmtDis = AmtDis.setScale(2); }else{ this.AmtDis = 0.00; }
        }
    }
    


public class ReturnWrapper {
    @AuraEnabled public List<wrapperInv> records;
    @AuraEnabled public Integer totalRecords;
    @AuraEnabled public String status;
}

 


}