force-app/main/default/objects/Account/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <formula>Agent_to_Bill__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agent_to_Bill__c.field-meta.xml
<CustomField>
    <fullName>Agent_to_Bill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <formula>breadwinner_qbo__Total_Amount_Due__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <formula>Indicated_Premium__c - (Indicated_Premium__c * VALUE(TEXT( Commission__c )))/100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_Address2__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address2__c</fullName>
    <label>Mailing Address 2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address__c</fullName>
    <label>Mailing Address</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State__c</fullName>
    <label>Mailing State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip_Code__c</fullName>
    <label>Mailing Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label>Number of Units</label>
    <precision>7</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_City__c.field-meta.xml
<CustomField>
    <fullName>Physical_City__c</fullName>
    <label>Physical City</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Applicants/Insureds</relationshipLabel>
    <relationshipName>Applicants_Insureds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Producer__c.field-meta.xml
<CustomField>
    <fullName>Producer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pxx</label>
    <referenceTo>Producer__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/QB_External_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>QB External Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/QB_Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_Parent_Id__c</fullName>
    <externalId>true</externalId>
    <label>QB_Parent_Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Amount_Received__c</fullName>
    <formula>Invoice__r.breadwinner_qbo__Amount_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address__c</fullName>
    <formula>Insured__r.Mailing_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mailing Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <formula>Insured__r.Number_of_Units__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Producer__c.field-meta.xml
<CustomField>
    <fullName>Producer__c</fullName>
    <formula>Insured__r.Agent_to_Bill__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Producer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/QB_Invoice__c.field-meta.xml
<CustomField>
    <fullName>QB_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QB Invoice</label>
    <referenceTo>QB_Invoice__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/QB_Status_Flag__c.field-meta.xml
<CustomField>
    <fullName>QB_Status_Flag__c</fullName>
    <formula>QB_Invoice__r.QB_Status_Flag__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Flag</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>from Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Policy</relationshipLabel>
    <relationshipName>Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CURRENT</fullName>
                <default>true</default>
                <label>CURRENT</label>
            </value>
            <value>
                <fullName>RENEWED</fullName>
            </value>
            <value>
                <fullName>NON-RENEWED</fullName>
            </value>
            <value>
                <fullName>CANCELLED - FULL REFUND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/QB_Invoice__c.object-meta.xml
<CustomObject>
    <label>QB Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QB Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QB Invoices</relationshipLabel>
    <relationshipName>QB_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <formula>Account__r.Agency_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Credited__c.field-meta.xml
<CustomField>
    <fullName>Amount_Credited__c</fullName>
    <description>Amount Credited will be calculated only if any Credit Memo applied to Invoice</description>
    <label>Amount Credited</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Amount_Received__c</fullName>
    <label>Amount Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Credit_Memo_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo_Total_Amount__c</fullName>
    <label>Total Credit / Refund Amoun</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/QB_External_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_External_Id__c</fullName>
    <label>QB External Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
ISBLANK( Internal_Status__c ),
CASE(
Type__c,

&apos;Sales Receipt&apos;, &apos;Paid&apos;,
&apos;Refund Receipt&apos;, &apos;Paid&apos;,

&apos;Invoice&apos;, IF( Amount_Overdue__c &gt; 0,
&apos;Overdue&apos;,
IF( Amount_Due__c &gt; 0,
IF( Amount_Received__c &gt; 0,
&apos;Partial&apos;,
&apos;Open&apos;
),
&apos;Paid&apos;
)
),

IF( Credit_Memo_Unallocated_Credit__c &gt; 0,
&apos;Unapplied&apos;,
&apos;Closed&apos;
)
),
Internal_Status__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Applicant_Insured__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Insured__c</fullName>
    <label>Applicant/Insured</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Date_of_Quote__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Quote__c</fullName>
    <label>Date of Quote</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <formula>Applicant_Insured__r.Number_of_Units__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Producer__c.field-meta.xml
<CustomField>
    <fullName>Producer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_Expires_in__c.field-meta.xml
<CustomField>
    <fullName>Quote_Expires_in__c</fullName>
    <label>Quote Expires in</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30 days</fullName>
                <default>true</default>
                <label>30 days</label>
            </value>
            <value>
                <fullName>60 days</fullName>
            </value>
            <value>
                <fullName>90 days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoiceListCtrl_Test.cls
@isTest
public class InvoiceListCtrl_Test {
    
    @isTest static void myTest1() { 
        Account agency             = new Account();
        agency.Number_of_Units__c  = 1;
        agency.Name                = 'Agency Account Name For Acc 1';
        agency.Physical_City__c    = 'City';
        agency.RecordTypeId        = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agencies').getRecordTypeId();
        insert agency;
        
        Contact producre   = new Contact();
        producre.LastName  = 'Test Producre';
        producre.FirstName = 'Test Producre';
        producre.AccountId = agency.Id;
        insert producre;
        
        Account applicant             = new Account();
        applicant.Number_of_Units__c  = 100;
        applicant.Name                ='Test Account Name For Acc 1';
        applicant.Physical_City__c    = 'City';
        applicant.Agent_to_Bill__c    = producre.Id;
        applicant.RecordTypeId        = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Insured').getRecordTypeId();
        insert applicant;
        
        QB_Invoice__c invoice           = new QB_Invoice__c();
        invoice.Policy__c              = '20222611C';
        invoice.Due_Date__c            = Date.newInstance(2022, 12, 9);
        invoice.Invoice_Date__c        = Date.newInstance(2022, 11, 9); 
        invoice.Amount_Received__c     = 1000.00;
        invoice.Amount_Credited__c     = 1000.00;
        invoice.Discount_Amount__c     = 1000.00;
        invoice.Amount_Due__c          = 1000.00;
        invoice.Total__c               = 1000.00; 
        invoice.Account__c 				= applicant.Id;
        invoice.Credit_Memo_Total_Amount__c     = 1000.00;
        
        insert invoice; 
        test.startTest();
        InvoiceListCtrl.getDataByFilter(invoice.Name);
        test.stopTest();
        
        //  InvoiceListCtrl.fetchInvoices();
    }
    
    
    @isTest static void myTest2() {
        Account acc              = new Account() ;
        acc.Number_of_Units__c   = 1;
        acc.Name                 ='Test';
        acc.Physical_City__c     = 'City';
        acc.Mailing_Address2__c  = 'Street2';
        acc.Mailing_Address__c   = 'Street';
        acc.Mailing_City__c      = 'Test';
        acc.Mailing_State__c     = 'IN';
        acc.Mailing_Zip_Code__c  = '4232';
        acc.QB_Parent_Id__c	     = 4532;
        acc.QB_External_Id__c	 = 55360;
        insert acc;
        
        
        Contact con                   = new Contact();
        con.AccountId                 = acc.id;
        con.LastName                  = 'Last';
        insert con;
        
        
        Account applicant             = new Account() ;
        applicant.Number_of_Units__c  = 100;
        applicant.Name                ='Test Account Name For Acc 1';
        applicant.Physical_City__c    = 'City';
        applicant.RecordTypeId        = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Insured').getRecordTypeId();
        applicant.Agent_to_Bill__c    = con.Id;
        applicant.QB_External_Id__c	  = 553562;
        insert applicant;
        
        Quote__c  quote            = new Quote__c();
        quote.Amount__c            = 100;
        quote.Date_of_Quote__c     = Date.newInstance(2022, 11, 9);
        quote.Quote_Expires_in__c  = '30 days';
        quote.Applicant_Insured__c = applicant.id;
        quote.Producer__c	     = con.Id;
        insert quote;
        
        QB_Invoice__c invoice          = new QB_Invoice__c();
        invoice.Policy__c              = '20222611D';
        invoice.Due_Date__c            = Date.newInstance(2023, 02, 16);
        invoice.Invoice_Date__c        = Date.newInstance(2023, 02, 03);
        invoice.Amount_Received__c     = 00.00;
        invoice.Amount_Credited__c     = 00.00;
        invoice.Discount_Amount__c     = 00.00;
        invoice.Amount_Due__c          = 399.00;
        invoice.Credit_Memo_Total_Amount__c     = 00.00;
        invoice.Total__c                        = 399.00; 
        invoice.Account__c 				= applicant.Id;
        invoice.InceptionDate__c           = system.today();
        invoice.InvoiceNumber__c           = 'INV-1147';
        invoice.Terms__c                  = 'Due on receipt';
        insert invoice; 
        QB_Invoice__c inv          = new QB_Invoice__c();
        inv.Policy__c              = '20222611D';
        inv.Due_Date__c            = Date.newInstance(2023, 02, 16);
        inv.Invoice_Date__c        = Date.newInstance(2023, 02, 03);
        inv.Amount_Received__c     = 00.00;
        inv.Amount_Credited__c     = 00.00;
        inv.Discount_Amount__c     = 00.00;
        inv.Amount_Due__c          = 399.00;
        inv.Credit_Memo_Total_Amount__c     = 00.00;
        inv.Total__c                        = 399.00; 
        inv.Account__c 				= applicant.Id;
        inv.InceptionDate__c           = system.today();
        inv.InvoiceNumber__c           = 'INV-1147';
        inv.Terms__c                  = 'Due on receipt';
        insert inv; 
        
       // List<QB_Invoice__c> qbinvoiceList = [SELECT Id,Agency__c,InvoiceNumber__c,Status__c,QB_Status_Flag__c,Name,Terms__c,Account__c,Account__r.Name,Due_Date__c,Invoice_Date__c,Inception_Date__c,Amount_Received__c,Amount_Credited__c,Amount_Due__c,Amount_Overdue__c,Discount_Amount__c,Credit_Memo_Total_Amount__c,Total__c FROM QB_Invoice__c WHERE Agency__c!= null AND Account__c!=null AND Id=:inv.Id AND Status__c = 'Open' ORDER BY Name DESC];
        
        Test.startTest();
      
        String result = InvoiceListCtrl.getInvoicesList(1,null,26,'DESC',true,'Name','closed');
        Test.stopTest();
    }
    @isTest static void myTest3() {
        
        Test.startTest();
        InvoiceListCtrl.getInvoicesList(1,null,1,null,false,null,'open');
        Test.stopTest();
    }
    @isTest static void myTest4() { 
        
        test.startTest();
        InvoiceListCtrl.getDataByFilter('');
        Test.stopTest();
    }
    
    
}