force-app/main/default/objects/Account/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <formula>Indicated_Premium__c - (Indicated_Premium__c * VALUE(TEXT( Commission__c )))/100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address__c</fullName>
    <label>Mailing Address</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State__c</fullName>
    <label>Mailing State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip_Code__c</fullName>
    <label>Mailing Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label>Number of Units</label>
    <precision>7</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_City__c.field-meta.xml
<CustomField>
    <fullName>Physical_City__c</fullName>
    <label>Physical City</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_State__c.field-meta.xml
<CustomField>
    <fullName>Physical_State__c</fullName>
    <label>Physical State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Physical_Street_Address__c</fullName>
    <label>Physical Address 2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Physical_Zip_Code__c</fullName>
    <label>Physical Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Applicants/Insureds</relationshipLabel>
    <relationshipName>Applicants_Insureds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Discount_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Discount_Value__c</fullName>
    <formula>(Indicated_Premium__c * VALUE(TEXT( Commission__c )))/100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Discount  Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Insured__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Insured__c.field-meta.xml
<CustomField>
    <fullName>Insured__c</fullName>
    <label>Insured</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>breadwinner_qbo__Invoice__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address__c</fullName>
    <formula>Insured__r.Mailing_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mailing Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <formula>Insured__r.Number_of_Units__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Previous_Policy__c.field-meta.xml
<CustomField>
    <fullName>Previous_Policy__c</fullName>
    <label>Previous Policy#</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/QB_Invoice__c.field-meta.xml
<CustomField>
    <fullName>QB_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QB Invoice</label>
    <referenceTo>QB_Invoice__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>from Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Policy</relationshipLabel>
    <relationshipName>Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Year_Built__c.field-meta.xml
<CustomField>
    <fullName>Year_Built__c</fullName>
    <formula>Insured__r.Year_Built__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year Built</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/QB_Invoice__c.object-meta.xml
<CustomObject>
    <label>QB Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QB Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QB Invoices</relationshipLabel>
    <relationshipName>QB_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>The e-mail address where the invoice is sent</description>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Email_Status__c.field-meta.xml
<CustomField>
    <fullName>Email_Status__c</fullName>
    <description>Email status of the invoice.
Values: NotSet, NeedToSend, EmailSent</description>
    <label>Email Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Inception_Date__c.field-meta.xml
<CustomField>
    <fullName>Inception_Date__c</fullName>
    <formula>Invoice_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inception Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Line_Item__c/QB_Line_Item__c.object-meta.xml
<CustomObject>
    <label>QB Line Item</label>
    <nameField>
        <label>QB Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QB Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <description>Master of the line item</description>
    <label>Invoice</label>
    <referenceTo>QB_Invoice__c</referenceTo>
    <relationshipLabel>QB Line Items</relationshipLabel>
    <relationshipName>QB_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QB_Line_Item__c/fields/Line_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Id__c</fullName>
    <description>Line Item reference Id</description>
    <label>Line Item Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Line_Item__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>Specifies the position of the line in the collection of transaction lines.</description>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Line_Item__c/fields/Product_Service__c.field-meta.xml
<CustomField>
    <fullName>Product_Service__c</fullName>
    <description>Name of Product/Service</description>
    <label>Product/Service</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Applicant_Insured__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Insured__c</fullName>
    <label>Applicant/Insured</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <formula>Applicant_Insured__r.Number_of_Units__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Open_Closed__c.field-meta.xml
<CustomField>
    <fullName>Open_Closed__c</fullName>
    <label>Open/Closed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Closed/Written</label>
            </value>
            <value>
                <fullName>Closed/Not Written</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteTriggerHandler.cls
public class QuoteTriggerHandler {
    
    // public static void CreatingPolicyAndInvoice(List<Quote__c> quoList) {
    //     List<Policy__c> polToBeInsertedList = new List<Policy__c>();
    //     for(Quote__c queObj : quoList ) {
    //         if(queObj.Open_Closed__c == '' ){
                
    //         }
    //         Policy__c polObj = new Policy__c();
    //         /*Quote__c accObj : [SELECT Id,Name,Applicant_Insured__r.Number_of_Units__c,Applicant_Insured__r.Year_Built__c,
    //         Applicant_Insured__r.Physical_Street_Address__c,Applicant_Insured__r.Mailing_Address__c,Applicant_Insured__r.Mailing_City__c,
    //         Applicant_Insured__r.Mailing_State__c,Applicant_Insured__r.Mailing_Zip_Code__c,Applicant_Insured__r.Physical_City__c,
    //         Applicant_Insured__r.Physical_State__c,
    //         Applicant_Insured__r.Physical_Zip_Code__c,Applicant_Insured__r.Phone,Applicant_Insured__r.Email__c FROM Quote__c];*/
    //         //polObj.Insured__c= applicant;
    //         polObj.Previous_Policy__c = 'srcgeydtd';
    //         polToBeInsertedList.add(polObj);
    //     }
    //     System.debug('Data '+polToBeInsertedList);
    //     if(!polToBeInsertedList.isEmpty()){
    //         System.debug('data');
    //         insert polToBeInsertedList;
    //         system.debug('data inserted '+polToBeInsertedList);
    //     }
    // }

    public static void CreatingInvoice(List<Quote__c> quoList) {
        List<QB_Invoice__c> invListToBeInserted = new List<QB_Invoice__c>();        
        List<QB_Line_Item__c>  lineItemLisTToBeInserted = new List<QB_Line_Item__c>();

        List<Product2> proList = [SELECT ID,Name FROM Product2 WHERE Name IN ('Gross Premium','Commissions') AND IsActive = true ORDER BY Name DESC];
        Integer count = 1;
        for(Quote__c queObj : quoList ) {

            if(queObj.Open_Closed__c == 'Closed' ){
                System.debug('Called Closed Condition');  
                
                System.debug('Applicat Id '+queObj.Applicant_Insured__c);
                
                Account applicant = [SELECT Id,Name,Discount_Amount__c,Total_Discount_Value__c,Email__c FROM Account WHERE Id =: queObj.Applicant_Insured__c LIMIT 1];
                
                
                System.debug('Amount      '+applicant.Discount_Amount__c);
                System.debug('Dis Amount  '+applicant.Total_Discount_Value__c);

                // Policy__c polObj = new Policy__c();
                QB_Invoice__c invoiceObj = new QB_Invoice__c();
                invoiceObj.Name       = 'INV-'+Math.round((Math.random() * (9000) + 1000));
                invoiceObj.Account__c = queObj.Applicant_Insured__c;
                invoiceObj.Invoice_Date__c = System.today();
                //invoiceObj.Inception_Date__c	 = System.today();
                invoiceObj.Policy__c = '20220808A';
                if(applicant.Email__c!=''){
                    invoiceObj.Email__c = applicant.Email__c;
                    invoiceObj.Email_Status__c = 'Set';
                }else{
                    invoiceObj.Email_Status__c = 'NotSet';
                }           
                
                //invListToBeInserted.add(invoiceObj);

                if(true){
                    insert invoiceObj;

                    for(Product2 proIte : proList){
                        QB_Line_Item__c  lineItemObj = new QB_Line_Item__c();
                        // CM-2206-LineItem-1
                        lineItemObj.Name = 'INV-2208-LienItem-'+count;
                        // // field value like as Name from ProList (Gross Premium)
                        lineItemObj.Product_Service__c = proIte.Name;
                        // Quanitity 1
                        lineItemObj.Quantity__c = 1;
                        // Rate Fatched from Applicant/ Issuerd
                        if(proIte.Name == 'Gross Premium'){
                            lineItemObj.Rate__c = applicant.Discount_Amount__c;
                            lineItemObj.Amount__c = applicant.Discount_Amount__c;
                        }else if(proIte.Name == 'Commissions'){
                            lineItemObj.Rate__c = applicant.Total_Discount_Value__c;
                            lineItemObj.Amount__c = applicant.Total_Discount_Value__c;
                        }
                        // Invoice Id
                        lineItemObj.Invoice__c = invoiceObj.Id;
                        // field value like as 1, 2
                        lineItemObj.Line_Number__c = count;
                        // field value like as 702594170-CM-1809-1, 702594170-CM-1809-2
                        lineItemObj.Line_Item_Id__c = '702594170-INV-1809-'+count;
                        // add in the list , need to be inserted
                        lineItemLisTToBeInserted.add(lineItemObj);
                        count++;
                    } 
    
                    if(!lineItemLisTToBeInserted.isEmpty()){
                        insert lineItemLisTToBeInserted;
                    }
                }

                
             
            }
            
            // polToBeInsertedList.add(polObj);
        } 
        // if(!invListToBeInserted.isEmpty()){
        //     System.debug('data');
        //     insert invListToBeInserted;
        //     system.debug('Data of Invoice '+invListToBeInserted);
        //     System.debug('Data of Lien Item '+lineItemLisTToBeInserted);
        //     for(QB_Invoice__c invIte : invListToBeInserted){

        //     }
        // }
    }
}