force-app/main/default/objects/Account/fields/Insured_Name__c.field-meta.xml
<CustomField>
    <fullName>Insured_Name__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Insured Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/QB_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_Customer_Id__c</fullName>
    <externalId>true</externalId>
    <label>QB Customer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/QB_Sync_Token__c.field-meta.xml
<CustomField>
    <fullName>QB_Sync_Token__c</fullName>
    <label>QB Sync Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QB_QuickBooksService.cls
public with sharing class QB_QuickBooksService {
    
    @future(callout=true)
    public static void createCustomerFromAccount(String accId){
        system.debug('Stage is RFP rewarded Anugrah, Manish Test');
        createCustomerFromAccountSync(accId);
    }
    public static void createCustomerFromAccountSync(String accId){
        System.debug('Create Customer From AccountId');
        String qbId = '';
        Account accObj = [SELECT Id,QB_Customer_Id__c,QB_Sync_Token__c,Name,Insured_Name__c,Mailing_City__c,Email__c,Phone FROM Account WHERE Id =: accId];
        //QB_External_API.createCustomer(accObj); 
             
    }
         
}