force-app/main/default/objects/Account/fields/Mailing_Address2__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address2__c</fullName>
    <label>Mailing Address 2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address__c</fullName>
    <label>Mailing Address</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State__c</fullName>
    <label>Mailing State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip_Code__c</fullName>
    <label>Mailing Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label>Number of Units</label>
    <precision>7</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_City__c.field-meta.xml
<CustomField>
    <fullName>Physical_City__c</fullName>
    <label>Physical City</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/applicantProducerCtrl_Test.cls
@isTest(SeeAllData=true)
public class applicantProducerCtrl_Test {
    @isTest static void myTest() {
          
        Account applicant              = new Account() ;
        applicant.Number_of_Units__c   = 1;
        applicant.Name                 ='Test';
        applicant.Physical_City__c     = 'City';
        applicant.Mailing_Address2__c  = 'Street2';
        applicant.Mailing_Address__c   = 'Street';
        applicant.Mailing_City__c      = 'Test';
        applicant.Mailing_State__c     = 'IN';
        applicant.Mailing_Zip_Code__c  = '4232';
        insert applicant;
        
        
        Contact con                   = new Contact();
        con.AccountId                 = applicant.id;
        con.LastName                  = 'Last';
        insert con;
        
        List<Contact>  conList    = [SELECT Name,AccountId FROM Contact WHERE Id =: con.id];
        Test.startTest();
        applicantProducerCtrl.getAccount(conList);
        Test.stopTest();    
    }
    
    @isTest static void myTest2() {
          
        Account applicant              = new Account() ;
        applicant.Number_of_Units__c   = 1;
        applicant.Name                 ='Test';
        applicant.Physical_City__c     = 'City';
      
        insert applicant;
        
        
        Contact con                   = new Contact();
        con.AccountId                 = applicant.id;
        con.LastName                  = 'Last';
        insert con;
        
        List<Contact>  conList    = [SELECT Name,AccountId FROM Contact WHERE Id =: con.id];
        Test.startTest();
        applicantProducerCtrl.getAccount(conList);
        Test.stopTest();    
    }
}