force-app/main/default/objects/Account/fields/Mailing_Address2__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address2__c</fullName>
    <label>Mailing Address 2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address__c</fullName>
    <label>Mailing Address</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State__c</fullName>
    <label>Mailing State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip_Code__c</fullName>
    <label>Mailing Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/applicantProducerCtrl.cls
public class applicantProducerCtrl {
    public static void getAccount(List<Contact> conList){
        List<Id> accId=new List<Id>();
        List<Contact> updtCon = New List<Contact>();
        contact con=new contact();
        for(Contact conItr:conList){
            if(conItr.AccountId!=null){
                accId.add(conItr.AccountId);
            }
        }
        
        List<Contact> prodList = new List<Contact>();
        List<Account> accList=[SELECT  id,Mailing_Address__c,Mailing_Address2__c,Mailing_City__c,Mailing_State__c,Mailing_Zip_Code__c 
                               FROM Account WHERE id IN:accId];
        String address1 = '',address2='' ;
        
        if(accList[0].Mailing_Address__c !=null || accList[0].Mailing_Address2__c!=null){
            if(accList[0].Mailing_Address__c !=null ){
                address1 = accList[0].Mailing_Address__c;
            }
               if(accList[0].Mailing_Address2__c !=null ){
                address2 = accList[0].Mailing_Address2__c;
            }
            con.MailingStreet = address1 + ' ' + address2;
        }else{
            con.MailingStreet ='';
        }
        if(accList[0].Mailing_City__c!=null){
            con.MailingCity = accList[0].Mailing_City__c;
        }else{
            con.MailingCity = '';
        }
        
        if(accList[0].Mailing_State__c !=null){
            con.MailingState = accList[0].Mailing_State__c;
        }else{
             con.MailingState='';
        }
        
        if(accList[0].Mailing_Zip_Code__c!=null){
             con.MailingPostalCode = accList[0].Mailing_Zip_Code__c;
        }else{
             con.MailingPostalCode='';
        }
       
        con.id=conList[0].id;
        updtCon.add(con);
        
        update updtCon;
    }
    
}