force-app/main/default/objects/Account/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label>Number of Units</label>
    <precision>7</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_City__c.field-meta.xml
<CustomField>
    <fullName>Physical_City__c</fullName>
    <label>Physical City</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Applicant_Insured__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Insured__c</fullName>
    <label>Applicant/Insured</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Date_of_Quote__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Quote__c</fullName>
    <label>Date of Quote</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <formula>Applicant_Insured__r.Number_of_Units__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_Expires_in__c.field-meta.xml
<CustomField>
    <fullName>Quote_Expires_in__c</fullName>
    <label>Quote Expires in</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30 days</fullName>
                <default>true</default>
                <label>30 days</label>
            </value>
            <value>
                <fullName>60 days</fullName>
            </value>
            <value>
                <fullName>90 days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/createCustomerCtrl_Test.cls
@isTest(SeeAllData=true)
public class createCustomerCtrl_Test {
    @isTest static void myTest() {
        
        Account applicant             = new Account() ;
        applicant.Number_of_Units__c  = 1;
        applicant.Name                ='Test';
        applicant.Physical_City__c    = 'City';
        insert applicant;
        
        
        Contact con                   = new Contact();
        con.AccountId                 = applicant.id;
        con.LastName                  = 'Last';
        con.FirstName                 = 'First';
        insert con;
        
        
        Quote__c  quote               = new Quote__c();
        quote.Amount__c               = 100;
        quote.Date_of_Quote__c        = Date.newInstance(2022, 11, 9);
        quote.Quote_Expires_in__c     = '30 days';
        quote.Applicant_Insured__c    = applicant.id;
        insert quote;
        
        

        createCustomerCtrl.getContacts(applicant.id);
        createCustomerCtrl.getAllDetailsOfApplicant(quote.id);
        createCustomerCtrl.getProducerDetails(quote.id); 
        createCustomerCtrl.getAllDetails(quote.id);
   }

    @isTest static void myTest2() {
        Account applicant             = new Account() ;
        applicant.Number_of_Units__c  = 1;
        applicant.Name                ='Test';
        applicant.Physical_City__c    = 'City';
        insert applicant;
        
        Account applicant2             = new Account() ;
        applicant2.Number_of_Units__c  = 1;
        applicant2.Name                ='Test';
        applicant2.Physical_City__c    = 'City';
        string account = String.valueOf(applicant2);
        createCustomerCtrl.creatingCustomer(account,applicant.id,applicant.Name );
        //QB_External_API.createCustomerAndSync(account,applicant.id);
      
        createCustomerCtrl.getContacts('');
    }
    
}