force-app/main/default/objects/Account/fields/Producer__c.field-meta.xml
<CustomField>
    <fullName>Producer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pxx</label>
    <referenceTo>Producer__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/QB_External_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>QB External Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/QB_Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_Parent_Id__c</fullName>
    <externalId>true</externalId>
    <label>QB_Parent_Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/QB_Sync_Token__c.field-meta.xml
<CustomField>
    <fullName>QB_Sync_Token__c</fullName>
    <label>QB Sync Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Producer__c/Producer__c.object-meta.xml
<CustomObject>
    <label>Old Producer</label>
    <nameField>
        <label>Producer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Old Producers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Applicant_Insured__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Insured__c</fullName>
    <label>Applicant/Insured</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Producer__c.field-meta.xml
<CustomField>
    <fullName>Producer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BindQuoteModalCtrl.cls
public without sharing class BindQuoteModalCtrl {
  
    @AuraEnabled
    public static Quote__c checkProducre(String quoteId){
        //System.debug('recprd Id '+quoteId);
        
        Quote__c quoteObj = [SELECT Producer__c,Applicant_Insured__r.QB_Sync_Token__c,Applicant_Insured__r.QB_External_Id__c,Applicant_Insured__r.QB_Parent_Id__c FROM Quote__c WHERE Id=:quoteId];         

        return quoteObj;

    }
}