force-app/main/default/objects/QB_Invoice__c/QB_Invoice__c.object-meta.xml
<CustomObject>
    <label>QB Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QB Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QB Invoices</relationshipLabel>
    <relationshipName>QB_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/qbGetCount.cls
public class qbGetCount {
    Public static void getCount(String recid){  
        Date dateToday = Date.today();
        String Month = String.valueof(dateToday.month());
        String Day = String.valueof(dateToday.day());
        if(Month.length()==1){
            Month = '0' + Month;
        }
        if(Day.length()==1){
            Day = '0' + Day;
        }
        String sToday = String.valueof(dateToday.year()) + Month + Day ;
        //System.debug(sToday);
       // List<Integer> Chars = New List<Integer>();
        String dateChar;
         AggregateResult qbCount = [SELECT Count(id) ctid FROM QB_Invoice__c WHERE Account__c =: recid];
        Integer ct = (Integer) qbCount.get('ctid');
        //System.debug(qbCount);
         dateChar = sToday + 'A';
        System.debug(dateChar);
        
        for(Integer i=0; i<ct; i++){
            if(i>=1){
                Integer charCode = 'A'.charAt(0);
                List<Integer> chars = new List<Integer>{charCode+i};
                
                    String nextChar = String.fromCharArray(Chars);
                //System.debug(nextChar);
                dateChar = sToday + nextChar;
                System.debug(dateChar);
            }
        }
        
        
    }
}