force-app/main/default/objects/QB_Invoice__c/QB_Invoice__c.object-meta.xml
<CustomObject>
    <label>QB Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QB Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Invoice__c/fields/Email_Status__c.field-meta.xml
<CustomField>
    <fullName>Email_Status__c</fullName>
    <description>Email status of the invoice.
Values: NotSet, NeedToSend, EmailSent</description>
    <label>Email Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Total_Tax__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax__c</fullName>
    <label>Total Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Line_Item__c/QB_Line_Item__c.object-meta.xml
<CustomObject>
    <label>QB Line Item</label>
    <nameField>
        <label>QB Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QB Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <description>Master of the line item</description>
    <label>Invoice</label>
    <referenceTo>QB_Invoice__c</referenceTo>
    <relationshipLabel>QB Line Items</relationshipLabel>
    <relationshipName>QB_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QB_Line_Item__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>Specifies the position of the line in the collection of transaction lines.</description>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CreateInvoiceExternalAPI.cls
global with sharing class CreateInvoiceExternalAPI {
    public CreateInvoiceExternalAPI() {

    }

    public static void CreateInvoice(List<QB_Line_Item__c> invoiceData){

     String JSONBody='{'+
       ' "Line": ['+
       '  {'+           
       '   "DetailType": "SalesItemLineDetail", '+
       '   "Amount"    : '+''+invoiceData[0].Amount__c+', '+
       '   "LineNum"   : '+''+invoiceData[0].Line_Number__c+', '+    
       '   "SalesItemLineDetail": {'+
       '     "ItemRef"  : {'+
       '        "name"  : "Services", '+
       '        "value" : "1"'+
       '      }'+
       '    }'+
       '   }'+
       '], '+
       '  "TotalTax": '+''+invoiceData[0].Invoice__r.Total_Tax__c+', '+
       '  "DueDate": '+'"'+invoiceData[0].Invoice__r.Due_Date__c+'",\n'+
       '  "CustomerRef": {'+
       '  "value": "1"'+
       '  "BillEmail": {'+
       '  "Address": '+' "'+invoiceData[0].Invoice__r.Email_Status__c+'"'+
       '}, '+
       '   "ShipAddr": {'+
       ' "City": "Middlefield",'+ 
       '  "Line1": "5647 Cypress Hill Ave.", '+
       '  "PostalCode": "94303", '+
       '  "Lat": "37.4238562", '+
       '  "Long": "-122.1141681", '+
       '  "CountrySubDivisionCode": "CA", '+
       '  "Id": "25"'+
       '},'+ 
      '  "EmailStatus":'+' "'+invoiceData[0].Invoice__r.Email_Status__c+'", '+
      '  "BillAddr": {'+
      '  "Line4": "Middlefield, CA  94303", '+
      '  "Line3": "5647 Cypress Hill Ave.", '+
      '  "Line2": "Sonnenschein Family Store", '+
      '  "Line1": "Russ Sonnenschein", '+
      '  "Long": "-122.1141681", '+
      '  "Lat": "37.4238562", '+
      '  "Id": "95"'+
      '},'+
       ' }'+
       ' }"';
       System.debug('JSON BODY :: ' +JSONBody);
       createInvoiceAPI(JSONBody);

    }
    @future(callout = true)
    public static void createInvoiceAPI(String JSBODY){
        String endpoint; 
        String result;
        String JsonBody=JSBODY;         
            System.debug('JSON Body:-'+JsonBody);
            HttpRequest req = new HttpRequest();
            HttpResponse res = new HttpResponse();
            Http http = new Http();
            endpoint = 'callout:QuickBookCredendial'+'/v3/company/4620816365236175040/invoice?minorversion=65';
            //req.setHeader('Authorization', header);
            req.setEndpoint(endpoint);
            req.setMethod('POST');
            req.setHeader('Content-Type', 'application/json');
            req.setHeader('accept', 'application/json');
            req.setBody(JsonBody);
            res = http.send(req);
            System.debug(req.getEndpoint());
            system.debug(res.getBody());
            System.debug('Status @@ '+res.getStatusCode());
            if(res.getStatusCode() == 200)
            {
                
                Map<String,Object> QueryResponseMap =(Map<String,Object>) JSON.deserializeUntyped(res.getBody());   
                // Map<String,Object> Customers =(Map<String,Object>) QueryResponseMap.get('Customer');  
                // System.debug('Customer Data @@ '+Customers); 
                // comObj.QB_Customer_ID__c = (String)Customers.get('Id');
                // comObj.QB_Sync_Token__c  = '0';
                // update comObj;
                // QB_Integration_Log_Utils.insertIntegrationLog(req, res, 'customerReadAll', 'Customer created Successfully');
                result = 'error';
            } else {
                 result = 'success';
            }

 
    }


}