force-app/main/default/objects/QB_Invoice__c/QB_Invoice__c.object-meta.xml
<CustomObject>
    <label>QB Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QB Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QB Invoices</relationshipLabel>
    <relationshipName>QB_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/QB_Status_Flag__c.field-meta.xml
<CustomField>
    <fullName>QB_Status_Flag__c</fullName>
    <formula>IF(
CONTAINS($User.UIThemeDisplayed, &apos;Theme4&apos;),

IF(
ISBLANK( Internal_Status__c ),
IF( OR(Status__c = &apos;Paid&apos;, Status__c = &apos;Closed&apos;),
IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/green-flag.png&quot;, &quot;Paid&quot;),
IF( Type__c = &apos;Credit Memo&apos;,
IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/yflag.png&quot;, &quot;Unapplied&quot;),
IF( Amount_Overdue__c &gt; 0,
IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/red-flag.png&quot;, &quot;Overdue&quot;) ,
IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/yflag.png&quot;, &quot;Open&quot; )
)
)
),
IF(OR(Internal_Status__c = &apos;Pending&apos;,Internal_Status__c = &apos;Open/Partial&apos;), IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/yflag.png&quot;,&quot;Open&quot;),
IF(OR(Internal_Status__c = &apos;Invoiced In Full&apos;,Internal_Status__c = &apos;Closed&apos;),IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/green-flag.png&quot;, &quot;Paid&quot;),IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/X.png&quot;, &quot;X&quot;)))
),

IF(
ISBLANK( Internal_Status__c ),
IF( OR(Status__c = &apos;Paid&apos;, Status__c = &apos;Closed&apos;),
IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Paid&quot;, 16, 16),
IF( Type__c = &apos;Credit Memo&apos;,
IMAGE(&quot;/img/samples/flag_yellow.gif&quot;, &quot;Unapplied&quot;, 16, 16),
IF( Amount_Overdue__c &gt; 0,
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;Overdue&quot;, 16, 16) ,
IMAGE(&quot;/img/samples/flag_yellow.gif&quot;, &quot;Open&quot;, 16, 16)
)
)
),
IF(OR(Internal_Status__c = &apos;Pending&apos;,Internal_Status__c = &apos;Open/Partial&apos;), IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/yflag.png&quot;, &quot;Open&quot; , 16, 16),
IF(OR(Internal_Status__c = &apos;Invoiced In Full&apos;,Internal_Status__c = &apos;Closed&apos;),IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Paid&quot;, 16, 16),IMAGE(&quot;https://s3.amazonaws.com/cdn.breadwinner/X.png&quot;, &quot;X&quot;, 16, 16)))
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Flag</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
ISBLANK( Internal_Status__c ),
CASE(
Type__c,

&apos;Sales Receipt&apos;, &apos;Paid&apos;,
&apos;Refund Receipt&apos;, &apos;Paid&apos;,

&apos;Invoice&apos;, IF( Amount_Overdue__c &gt; 0,
&apos;Overdue&apos;,
IF( Amount_Due__c &gt; 0,
IF( Amount_Received__c &gt; 0,
&apos;Partial&apos;,
&apos;Open&apos;
),
&apos;Paid&apos;
)
),

IF( Credit_Memo_Unallocated_Credit__c &gt; 0,
&apos;Unapplied&apos;,
&apos;Closed&apos;
)
),
Internal_Status__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetInvoiceCtrl.cls
public without sharing class GetInvoiceCtrl {

    @AuraEnabled(cacheable=true)
    public static Integer getInvoiceCount(String recId) {
        Integer countVal = 0;
        Integer count = [SELECT Count() FROM QB_Invoice__c WHERE Account__c =:recId];
        return count;
    }

    @AuraEnabled(cacheable=true)
    public static Boolean getGetRecordType(String recId) {
        system.debug('getGetRecordType Record Id'+recId);
        Boolean isShow = false ;
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Insured').getRecordTypeId();
        Account  accObj = [SELECT RecordTypeId FROM Account WHERE Id =:recId];
        if(accObj.RecordTypeId  == devRecordTypeId){
            isShow = true;
        }else{
            isShow = false;
        }
        return isShow;
    }

    @AuraEnabled(cacheable=true)
    public static String getInvoiceRecords(String recId) {
        try {
            system.debug('recId'+recId);
            List<wrapperInv> warpperList = new List<wrapperInv>();
        List<QB_Invoice__c> invList = [SELECT Id,QB_Status_Flag__c,InvoiceNumber__c,Status__c,Name,Due_Date__c FROM QB_Invoice__c WHERE Account__c =:recId ORDER BY createddate DESC ];

        Integer i = 1; 
        if(!invList.isEmpty()){
                   for(QB_Invoice__c invIte : invList){ 
                    wrapperInv wraObj = new wrapperInv(i,invite.Id,invite.InvoiceNumber__c,invite.QB_Status_Flag__c,invite.Name,invite.Status__c,invite.Due_Date__c);
                    warpperList.add(wraObj); 
                    i++;
                }  
            return JSON.serialize(warpperList);  }else{  return null;   }  } catch (Exception e) { throw new AuraHandledException(e.getMessage());
            
            }

        
}
public class wrapperInv{
    @AuraEnabled   
    public Integer SrNo;
    @AuraEnabled   
    public String  InvoiceName;
    @AuraEnabled   
    public String Status;
    @AuraEnabled   
    public String  StatusFlag;
    @AuraEnabled   
    public Date  duedate;
    @AuraEnabled   
    public String  Flag;
    @AuraEnabled   
    public String  Id;
    @AuraEnabled   
    public List<String> FlagArray;

    public wrapperInv(Integer SrNo,String Id,String invoiceNumber,String  StatusFlag,String  InvoiceName,String Status, Date  duedate){
        this.SrNo = SrNo;
        this.Id   = Id;
        // this.StatusFlag = StatusFlag;
        if(invoiceNumber == null){
            this.InvoiceName = InvoiceName;
        }else{
            this.InvoiceName =invoiceNumber;
        }
     
        this.Status = Status;
        this.duedate = duedate;
        this.FlagArray   = StatusFlag.split('"');
        this.StatusFlag   = this.FlagArray[1];

    }
    }
}